### ISSUE TITLE
Grid and Rectilinear infil not continuous

### ISSUE THREAD

**Issue by Sidic101** [supermerill/Slic3r#103]
### Version
latest (1.43.0?)

### Operating system type + version
Windows 10 pro version 1903

### 3D printer brand / version + firmware version (if known)
irrelevant

### Behavior
The infil patern changes based on outer geometry, causes unwated internal bridging
![Annotation 2019-10-15 202048](https://user-images.githubusercontent.com/25415862/66858550-cd928380-ef89-11e9-8ebb-58d98f613395.png)
PrusaSlicer 2.1 on the left, Slic3r++ 1.43.0 on the right

**Comment by supermerill** [comment]
Can you drop here the .3mf (save as) ?

**Comment by Sidic101** [comment]
Here you go, it's zipped because Github doesn't allow 3mf files.


[PSU.zip](https://github.com/supermerill/Slic3r/files/3734129/PSU.zip)
