### ISSUE TITLE
Bridge & Solid Infill problems 

### ISSUE THREAD

**Issue by Alphaelectric** [supermerill/Slic3r#125]
### Version
Slic3r++ 2.1.44

### Operating system type + version
Windows 10 64Bit

### 3D printer brand / version + firmware version (if known)
Ender 3 + Marlin 2.0 Bugfix 

### Behavior
Slic3r++ creates infill that is excessively hard to print and may lead to longer prints (see attached images). 
The problem manifests itself in areas that require a lot of bridging. Both PrusaSlicer 2.1 and Cura 4.1 create a uniform ceiling on top of the areas to bridge. Slic3r++ creates a lot of different patches with bridge infill.

The second part of the problem is the solid layer that is printed on top of the bridge infill. As the screenshots show, PrusaSlicer 2.1 as well as Cura 4.1 create a uniform layer that is easy to print. Slic3r++ does not create such a uniform pattern. Instead it creates lots of small islands that are difficult to print and take far longer than required. 

The actual result was a failed print due to collision. 

Screenshots are taken from Slic3r++ and PrisaSlicer 2.1 for comparison of the same area and layer height. 
Slic3r++ Previews:
![Bug_Slicer++_BridgeInfill](https://user-images.githubusercontent.com/36924666/70396431-41d92880-1a09-11ea-940b-69923a9b09c9.jpg)
![Bug_Slicer++_SolidInfill](https://user-images.githubusercontent.com/36924666/70396432-41d92880-1a09-11ea-93c3-3e07936f389c.jpg)

PrusaSlicer Previews:
![PrusaSlicer_ _Cura_BridgeInfill](https://user-images.githubusercontent.com/36924666/70396433-41d92880-1a09-11ea-8ac4-9227596c1798.jpg)
![PrusaSlicer_ _Cura_SolidInfill](https://user-images.githubusercontent.com/36924666/70396430-41409200-1a09-11ea-817e-cd2aa797b91d.jpg)

**Comment by supermerill** [comment]
1) uncheck "more perimeters"
2) increase "margin: Default"  (by 2/3)

**Comment by Alphaelectric** [comment]
Thanks for your help. Unchecking "Extra Perimeters" makes it better, however, some pockets still remain. I cannot find the value for "margin". What exactly are you referring to? I am using the english language GUI,
![Slicer++_No Extra Perimeters_Solid](https://user-images.githubusercontent.com/36924666/70505569-9cb57180-1b28-11ea-9891-9bc35c8cfcf0.jpg)
![Slicer++_No Extra Perimeters_BridgeInfill](https://user-images.githubusercontent.com/36924666/70505571-9d4e0800-1b28-11ea-9b1e-346975c3bf41.jpg)

**Comment by supermerill** [comment]
infill -> Anchor solid infill by X mm -> default is for growing the top layer (and all solid below). Bridge is for growing the bridge layer and all solid layer above. So i think you want to increase the bridge anchor a bit here (not the default)

**Comment by Alphaelectric** [comment]
That did it! At 440% the sliced image was almost identical to the other results. I will do test prints to verify.
