### ISSUE TITLE
Suporting dense layers with "Automatic" algorithm not working?

### ISSUE THREAD

**Issue by Sebastianv650** [supermerill/Slic3r#13]
I'm using 1.41.1-5 and playing around with the new options. When I enable "Suporting dense layers" with algorithm automatic, nothing changes before a solid layer. Only "Anchored" inserts a denser infill layer. Is this a bug or a misunderstanding of it's way of working?

Screenshot of infill with "Automatic" just before the first real solid layer:
![grafik](https://user-images.githubusercontent.com/10776877/49599310-f5d04f80-f980-11e8-90d6-2896224fc31c.png)

**Comment by supermerill** [comment]
I recently had the same problem. Maybe i added a switch to prevent the dense infill on "full" areas. I have to remove it.

**Comment by supermerill** [comment]
should be fixed in 1.41.2-1

**Comment by Sebastianv650** [comment]
It is, thanks!
