### ISSUE TITLE
Please open pull request for the looping perimeters feature

### ISSUE THREAD

**Issue by douggorgen** [supermerill/Slic3r#132]
### Version
[alpha] no seam edition

### Operating system type + version
Windows 10 64 bit
### 3D printer brand / version + firmware version (if known)
Ender 3 Pro
### Behavior
I'm new to github so if this is not the right place for this, please let me know where I should request this.

@supermerill please open a pull request to include your perimeter looping feature into PrusaSlicer.

This is an incredibly useful and valuable feature for the following reasons:

1) It drastically reduces and in some cases eliminates the need for dialing-in retractions, wipes, and unretractions, thus saving time and resources spent on mutiple prints.

2) It drastically reduces and in some cases eliminates the need for sanding and cleanup on prints.

3) It is particularly useful for prints that involve moving parts where zits and blobs can cause interference between moving parts or even fuse them together thus causing the print to be useless.

_Is this a new feature request?_

**Comment by supermerill** [comment]
> It is particularly useful

Thank you, but i'm not the one that need to be convinced. Also, this feature your has been sponsored by gotthalmseder, see https://github.com/slic3r/Slic3r/issues/4552, so you may want to also thank him.

> please open a pull request to include your perimeter looping feature into PrusaSlicer.

Sorry but i won't. it takes me time to do that and there is a very high risk that i'll do that for nothing.
I need to have a request from the prusa team that they want this feature. It cost them time to review & accept it, and they will need to maintain it over time.
