### ISSUE TITLE
Mac Version crashes when trying to import printer profiles or add a new printer

### ISSUE THREAD

**Issue by audiorazor** [supermerill/Slic3r#134]
### Operating system type + version
MacOS 10.15.2

### 3D printer brand / version + firmware version (if known)
Prusa MK3S

### Behavior
When I try to import stock prusa profiles or add a new printer it crashes.  I have attached a picture of the error it throws. 
<img width="444" alt="Screenshot 2019-12-26 10 41 55" src="https://user-images.githubusercontent.com/14953137/71481686-ee1e5b80-27cc-11ea-82f9-3b0365d6f825.png">

**Comment by audiorazor** [comment]
sorry, didnt realize this was already posted.

**Comment by supermerill** [comment]
just relaunch, it should resolve itself.
Or remove basic.ini and creality.ini from resources/profiles
