### ISSUE TITLE
Use Part Fan to Cool Hotend turns off fan after completing

### ISSUE THREAD

**Issue by Eboman123** [supermerill/Slic3r#136]
This is my first "issue" post ever, so please let me know if there's anything I can do to be "better".

I've been exclusively using the supermerill version for the past couple of months.  Very impressed so far.  Over Christmas, I started doing some MMU prints with my Prusa and found a small problem.  Under "Filament-Advanced Settings", if I enable Multimaterial Toolchange Temperature and select Use Part Fan to Cool Hotend....it works as intended, but then turns the fan off completely until the NEXT filament change.  For example, I usually print PLA at 100% fan.   I also selected 100% during the tool change.  The ran runs at 100%....then runs at 100% during the toolchange to cool down the hotend.  But once the change is completed, the fan turns off completely until it's time to do the next filament change.  

Thanks!
Eric

P.S.  Setting the default Fan Speed to 100% and Turning OFF the Use Part Fan To Cool Hotend works just fine as long as 100% speed all the time is OK with you.

**Comment by supermerill** [comment]
ideally, you should save your project, zip it and drag-drop it here, so it's easier for me to reproduce.
Other that that, thaks for the report. I'll take a look.
