### ISSUE TITLE
Thin wall bug (2.2.47)

### ISSUE THREAD

**Issue by neophyl** [supermerill/Slic3r#138]
### Version
2.2.47.0 UI edition

### Operating system type + version
Windows 10 64 bit

### 3D printer brand / version + firmware version (if known)
Sliced for a modified cr10 with direct drive and 0.6 nozzle

### Behavior
I was using the latest ++ release to slice a project and give it a bit of a test at the same time.  The same project sliced fine in the previous prusa slicer releases (and also slices fine in 2.2.0 alpha2).

With 2.2.47 though there was a stl file that I just couldn't get to slice properly at all.  There's bits missing, I know this is usually down to bad model geometry but no errors showing for the part.  Also the prusa version slices it no problem so I don't think its the model.

Prusa 2.2.0 alpha 2
![sliced in 2 20_alpha](https://user-images.githubusercontent.com/46955527/72210261-86486000-34b0-11ea-8719-3210147b00b0.png)

Slicer ++ 2.2.47.0
![sliced in 2 2 47](https://user-images.githubusercontent.com/46955527/72210265-9a8c5d00-34b0-11ea-9c3b-3f1f1173011a.png)

I have tried thin wall detection on/off, with values going down to 10%.  Tried adjusting perimeter sizes etc but nothing I have tried gets it to slice properly.

I saved the project with just the problem part  and confirmed that it still had problems with just that part used.  Project attached.  Hopefully someone can figure out why it has a problem.

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs

[catch_test.3mf.zip](https://github.com/supermerill/Slic3r/files/4049830/catch_test.3mf.zip)
(just renamed it with zip on the end)

**Comment by supermerill** [comment]
It's a bug in the thin wall algorithm, maybe.
To return to a good (prusa-like) behavior, enable "overlapping perimeters".

**Comment by neophyl** [comment]
As this is now fixed I guess I should close ti :)
