### ISSUE TITLE
XY compensation for first layer, empty G1 codes

### ISSUE THREAD

**Issue by albert2004** [supermerill/Slic3r#141]
### Version
2.2.47.0

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
No matter

### Behavior
* slice 3 small objects

#### Project File (.3MF) where problem occurs
Issue 1:
First layer compensation (-0.2mm) does not work for thin walls. First layer is exactly this same as second one. In compare to PrusaSlices 2.2.0 alpha2, there is smaller first layer (and consistent according to new feature to adaptive compensation.
Supermerill version:
![xy_super](https://user-images.githubusercontent.com/30234261/72237701-b4768e80-35db-11ea-998c-702028eda72e.jpg)
![xy_02mm jpeg](https://user-images.githubusercontent.com/30234261/72237706-b7717f00-35db-11ea-8b8d-3edb16be1970.jpg)
PrusaSlicer version:
![xy_prusa_2](https://user-images.githubusercontent.com/30234261/72237730-cc4e1280-35db-11ea-9f54-828f934e8f34.jpg)
![xy_prusa](https://user-images.githubusercontent.com/30234261/72237732-cfe19980-35db-11ea-90a2-7abe18c54d62.jpg)

Issue 2:
In generated gcode, there are existing empty G1 codes (not existing in PrusaSlicer, 
see lines 800-900), like:

G1 X23.771 Y35.780 E0.00037
G1
G1 X23.752 Y35.825 E0.00057
G1
G1 X23.734 Y35.870 E0.00077
G1
G1 X23.691 Y35.955 E0.00189
G1
G1 X23.667 Y35.995 E0.00130
G1 X23.603 Y35.958 E0.00205
G1
G1 X23.539 Y35.922 E0.00158
G1 X23.053 Y35.417 E0.01506

Attached project and output gcodes from Supermerill and PrusaSlicer:
[Issue.zip](https://github.com/supermerill/Slic3r/files/4052401/Issue.zip)

**Comment by albert2004** [comment]
for XY compensation creates compilation error on linux / gcc 9.2.
In provided fix, you changed 2 functions:
ExPolygons _offset_holes(double hole_delta, const ExPolygons &input) const;
ExPolygons _smooth_curves(const ExPolygons &input, const PrintRegionConfig &conf) const;
in both of them, return value is specified under "if" and gc

**Comment by albert2004** [comment]
for XY compensation creates compilation error on linux / gcc 9.2.
/var/tmp/portage/media-gfx/slic3r-supermerill-9999/work/slic3r-supermerill-9999/src/libslic3r/PrintObject.cpp:2387:1: error: control reaches end of non-void function [-Werror=return-type]
/var/tmp/portage/media-gfx/slic3r-supermerill-9999/work/slic3r-supermerill-9999/src/libslic3r/PrintObject.cpp:2496:1: error: control reaches end of non-void function [-Werror=return-type]

**Comment by supermerill** [comment]
I corrected it in the branch 'stable'. I didn't merged it with master yet.
