### ISSUE TITLE
0° Bridge angle does not align bridging to axis.

### ISSUE THREAD

**Issue by BlazingBlackBeard** [supermerill/Slic3r#142]
### Version
2.2.47
### Operating system type + version
Windows 10 Pro 64 BIT

### 3D printer brand / version + firmware version
N/A

### Behavior
Configuring  a 0° angle for bridging angle does not align bridging to an axis, it will just default to the infill angle of 45° and try to bridge diagonally, not using the shortest path across gaps.

Reproducing this problem is easy, just load a model with a long and narrow bridging area, like the Skelestruder Mosquito mount and when it's sliced at an angle of 0° bridging, it will show in all it's glory.

![Slic3r++ bridging error](https://user-images.githubusercontent.com/57399529/72247599-22778180-35ed-11ea-8f24-724e35aaca4a.png)

#### Project File (.3MF) where problem occurs

[SP_cageB_mosquito.3mf.txt](https://github.com/supermerill/Slic3r/files/4053127/SP_cageB_mosquito.3mf.txt)

Example of correct bridging orientation in PrusaSlicer

![PrusaSlicer correct bridging](https://user-images.githubusercontent.com/57399529/72249135-a8e19280-35f0-11ea-86c4-59b7936443d2.png)

**Comment by kwaad2** [comment]
Disabling "Only one perimeter on Top surfaces" is the solution, so I would assume the issue lies within that.

**Comment by BlazingBlackBeard** [comment]
> Disabling "Only one perimeter on Top surfaces" is the solution, so I would assume the issue lies within that.

I'm not sure anyone would agree that disabling one unrelated feature should be neccesary to have bridging settings work as intended.

This is xlearly a bug that needs fixing properly so that bridging angles can be set independently of other unrelated settings, not hacked or worked-around just to make it behave as intended at the expense of other unrelated features.

Granted, as a temporary fix people could disable single perimeter tops but this should only be temporary and a proper fix implemented so that unrelated functions work as intended, in combination. I've not tried it yet so I don't know whether it actually allows bridging to be properly set. These options should not affect eachother.

**Comment by supermerill** [comment]
Currently, bridging angle is given by an obscure algorithm that tries to simulate different configuration and use the one that seems the best.
It's not an easy task, as I need to identify what's wanted (the conf with most short lines?, the one with the less long one?), and how to get it. So, sadly it may take some time.

For the "bridging angle", i have to look at what uses it.

**Comment by supermerill** [comment]
For this particular piece:
* a volume in the layer at 6.44/6.60 is only composed of 2 layers. So with "only one perimeter on top", some perimeters are pushed back as overhang, and it's bad.
* using "no perimeters on bridge" -> "keep only bridges" resolve this problem (it's not perfect, but it's much much better). I didn't see any other place where this setting will create problem, so i didn't put it in a modifier mesh.

[SP_cageB_mosquito.3mf.v2.zip](https://github.com/supermerill/Slic3r/files/4055488/SP_cageB_mosquito.3mf.v2.zip)

**Comment by kwaad2** [comment]
I would also like to point out that in Slic3r a 0 degrees for bridging is the default for "auto-generate" If you use 180, it will force generate the supports in the direction you want.
![image](https://user-images.githubusercontent.com/28718864/72304841-71e29f80-3637-11ea-9b44-74edded5ee33.png)

**Comment by supermerill** [comment]
For the next version, the "bridging angle" setting will be enforced if not 0 (instead of being used as an default value for the algorithm).

**Comment by supermerill** [comment]
With latest release
![image](https://user-images.githubusercontent.com/6536403/72456654-691fd400-37c5-11ea-8159-f937c73b3731.png)
[SP_cageB_mosquito_v3.3mf.zip](https://github.com/supermerill/Slic3r/files/4066321/SP_cageB_mosquito_v3.3mf.zip)
