### ISSUE TITLE
Support enforcers do not work and are bugged.

### ISSUE THREAD

**Issue by BlazingBlackBeard** [supermerill/Slic3r#143]
### Version
2.2.47

### Operating system type + version
Windows 10 Pro 64 BIT

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
When adding support enforcers under bridges, with the 'Don't support bridges' option deselected, supports are not generated under the part. However, in PrusaSlicer support enforcers are correctly generated for the same part and enforcer.

![Slic3r++ failed enforcers](https://user-images.githubusercontent.com/57399529/72250044-a2ecb100-35f2-11ea-9826-a03f1e564433.png)

![Slic3r++ bridging error](https://user-images.githubusercontent.com/57399529/72250191-ec3d0080-35f2-11ea-9515-2c8c83e82927.png)

#### Project File (.3MF) where problem occurs
[SP_cageB_mosquito.3mf.txt](https://github.com/supermerill/Slic3r/files/4053177/SP_cageB_mosquito.3mf.txt)

Example of PrusaSlicer correctly applying support enforcers:

![PrusaSlicer correct enforcers](https://user-images.githubusercontent.com/57399529/72250127-cd3e6e80-35f2-11ea-9245-d59ff3ccd069.png)

![PrusaSlicer correct support enforcers](https://user-images.githubusercontent.com/57399529/72250138-d29bb900-35f2-11ea-816b-9e2da0215903.png)

**Comment by supermerill** [comment]
it's resolved?

**Comment by BlazingBlackBeard** [comment]
Settings oversight, no problem here.
