### ISSUE TITLE
Current Nightly Build 2.2.47.0 requires MacOS 10.14

### ISSUE THREAD

**Issue by neonnt** [supermerill/Slic3r#145]
LSMinimumSystemVersion in info.plist must be changed from 10.14 to 10.13

`<key>LSMinimumSystemVersion</key>
    <string>10.14</string>`

After editing info.plist its working.

Also i have to thank you for your Slic3r Mods and MacOS Build. Best Slicer!

**Comment by supermerill** [comment]
this one? 
https://github.com/supermerill/Slic3r/suites/402664963/artifacts/1146129

**Comment by supermerill** [comment]
is https://github.com/supermerill/Slic3r/suites/403220301/artifacts/1152133 ok?

**Comment by neonnt** [comment]
yes, https://github.com/supermerill/Slic3r/suites/403220301/artifacts/1152133 ist working without any changes now :-)
