### ISSUE TITLE
Supporting dense layer infill doesn't succesfully anchor on low infill percentage.

### ISSUE THREAD

**Issue by JS3910** [supermerill/Slic3r#146]
### Version
The Mac version posted last in issue 129, says version 2.2.47+UNKNOWN in file info. The about box is empty.

### Operating system type + version
MacOS 10.14.5

### Behavior
When infill is set to a low percentage, here 10%, the anchoring doesn't make sure that it actually extends to the nearest infill line, it seems to just be a set distance around the hole. Expected behavior would be that it extends to a place where the lines would actually be anchored to.

![Screenshot 2020-01-18 at 18 00 29](https://user-images.githubusercontent.com/31373791/72668106-ac777e00-3a23-11ea-9576-963a0364422c.png)
![Screenshot 2020-01-18 at 18 00 23](https://user-images.githubusercontent.com/31373791/72668107-ac777e00-3a23-11ea-8a0c-f1f3bf49e64c.png)
![Screenshot 2020-01-18 at 18 00 39](https://user-images.githubusercontent.com/31373791/72668105-abdee780-3a23-11ea-97c5-9c90e359447a.png)

[Laser Camera Base.3mf.zip](https://github.com/supermerill/Slic3r/files/4081270/Laser.Camera.Base.3mf.zip)

**Comment by supermerill** [comment]
Look at the algorithm it uses and the tooltip.

'Anchor' means 'enlarged by the anchor setting you see below'
'Automatic' means 'be sure to not turn where there are no perimeter'.

Maybe i should rename it...

The best you can do, imho is to increase the parameter on this layer (see 
[Laser Camera Base v2.3mf.zip](https://github.com/supermerill/Slic3r/files/4081733/Laser.Camera.Base.v2.3mf.zip) )
Or you can change it to automatic, but it will create much more "dense support", to be safe.

![image](https://user-images.githubusercontent.com/6536403/72670220-747c3500-3a3b-11ea-9fb4-926ce5cf127a.png)

**Comment by JS3910** [comment]
Oh, yes that was not obvious from the available options! The other settings generate this big sort of big grid pattern so "automatic" I presumed would just make it ... good enough that the solid infill layer can be printed succesfully :).
