### ISSUE TITLE
Mac version has wrong bundle identifier

### ISSUE THREAD

**Issue by JS3910** [supermerill/Slic3r#148]
### Version
The Mac version posted last in issue 129, says version 2.2.47+UNKNOWN in file info. The about box is empty.

### Operating system type + version
MacOS 10.14.5

### Behavior
The bundle identifier in info.plist is still set to "com.prusa3d.slic3r/" which means some system wide settings are applied to both PS and S++ as they are considered the same application. It should be changed to something unique, like "com.supermerill.slic3r/". You can pick pretty much whatever you want that follows the format documented here:

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier

**Comment by supermerill** [comment]
should be okay with https://github.com/supermerill/Slic3r/suites/408481011/artifacts/1208976
