### ISSUE TITLE
Thin walls not slicing correctly

### ISSUE THREAD

**Issue by vi-kings** [supermerill/Slic3r#150]
### Version
2.2.47.1

### Operating system type + version
Windows 10 Jan 2020 Update

### 3D printer brand / version + firmware version (if known)
Prusa MK3S + 3.8.1 fw

### Behavior
When trying to slice thin details without the "Thin walls" options enabled slicer++ just cuts them off whereas PrusaSlicer does them

Steps needed to reproduce the problem:

1. Import the attached 3mf and slice.

Slicer++
![top1](https://user-images.githubusercontent.com/9168980/72686855-91267480-3af0-11ea-933d-50a6863c8444.PNG)

PrusaSlicer
![Prusaslicertop](https://user-images.githubusercontent.com/9168980/72686856-971c5580-3af0-11ea-81c8-f7ed9f49f92e.PNG)

You can activate the "Thin Walls" option, but still it doesn't look as nice.
Also it seems only to have one Perimeter even though I set it have at least three for testing.

### Files

[Bridging_100mm.zip](https://github.com/supermerill/Slic3r/files/4083327/Bridging_100mm.zip)

**Comment by supermerill** [comment]
use 'overlapping perimeters'
