### ISSUE TITLE
Feature request: compatibility with macOS Catalina

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#155]
### Version
_2.2.47 and newer_

### Operating system type + version
_macOS Catalina 10.15.3 (19D76)_

### 3D printer brand / version + firmware version (if known)
_irrelevant_

### Request:
__I wonder if it was possible to make the untested macOS builds compatible with macOS Catalina 10.15.
I would be really happy to replace PrusaSlicer with Slic3r ++, as I see options that have been missing for too long in PS. But my work environment is Catalina and, perhaps also because of my poor skills, I was unable to compile from the sources.__

**Comment by liftbag** [comment]
I managed to start slic3r++ on Catalina!
The steps I followed:
- Installed on Mojave
- Fixed icon display
- I started the application and configured it
- Closed Mojave I started Catalina
- Copied the executable from Mojave's Applications folder to the Catalina Applications folder.
At this point the program started normally.

**Comment by liftbag** [comment]
It seem to be a permission issue.

<img width="777" alt="Schermata 2020-02-03 alle 13 47 55" src="https://user-images.githubusercontent.com/14921654/73654417-f0a58800-468b-11ea-8b97-b57df810925d.png">

**Comment by supermerill** [comment]
I'll add a chmod in the build script.

How did you fix the icon display?
what's the "configuration" you did?

**Comment by liftbag** [comment]
> I'll add a chmod in the build script.
> 
> How did you fix the icon display?
> 

For some reason the slic3r.icns icon in Contents/resources is not displayed in the app launcher.
Here you can see how it appears (I renametd it slic3r+++ to allow parallel installation)

<img width="309" alt="Schermata 2020-02-03 alle 14 26 14" src="https://user-images.githubusercontent.com/14921654/73656802-2bf68580-4691-11ea-86a8-3052ed1f955d.png">

**Comment by liftbag** [comment]
> what's the "configuration" you did?
>

The normal configuration wizard on first startup.

**Comment by liftbag** [comment]
Here the differences of permissions between the application imported from Mojave and the one installed directly on Catalina. The executable flag appears to be missing.

<img width="777" alt="Schermata 2020-02-03 alle 14 38 11" src="https://user-images.githubusercontent.com/14921654/73657568-d28f5600-4692-11ea-8d6e-653ac8a09e62.png">

**Comment by supermerill** [comment]
Oh, it's the zip operation that brake it. I'll do something.

**Comment by liftbag** [comment]
Thanks for your time. I am getting familiar with this PrusaSlicer on steroids and I like it a lot.
Thank you so much for your great job!

**Comment by liftbag** [comment]
Actually
`chmod +x <path_to_Slic3r++>/Contents/MacOS/slic3r++`
do the job.

**Comment by supermerill** [comment]
can you test the dmg.zip here?
https://github.com/supermerill/Slic3r/actions/runs/34323886

and the tar.zip if it's not working as intended.

**Comment by liftbag** [comment]
> can you test the dmg.zip here?
> https://github.com/supermerill/Slic3r/actions/runs/34323886
> 
> and the tar.zip if it's not working as intended.
>

Both work perfectly! Only the icon is missing, but it's not a problem.

**Comment by antst** [comment]
Just in case, as it was here, icon issue on Catalana is related to wrong case
Contents/resources/slic3r.icns must be Contents/resources/Slic3r.icns
