### ISSUE TITLE
[Feature Request] Non Planar Slicing

### ISSUE THREAD

**Issue by abdbeg** [supermerill/Slic3r#158]
Hi

Thanks for all your work,  it would be very nice if you can implement this: https://github.com/Zip-o-mat/Slic3r/tree/nonplanar , nonplanar option for the slicer, that guy already made it for old Slic3r version, it would be nice if you can add it to your, thanks.

**Comment by supermerill** [comment]
duplicate of #84
Please comment the other issue.

The creator said it's not ready for integration and he wants to modify it before. So for the moment, I wait.

**Comment by abdbeg** [comment]
Sorry, i didn't find it, thanks!
