### ISSUE TITLE
Weird ironing behavior

### ISSUE THREAD

**Issue by Murloc992** [supermerill/Slic3r#16]
### Version
Slic3r++ 1.41.2-1 Win32 release

### Operating system type + version
Windows 10

### Behavior
Setting the attached STL to 100%, the generated preview and the print does some weird bridging moves while sanding on the same layer. Any ideas what can be done to fix this issue?

![image](https://user-images.githubusercontent.com/3779847/49889243-b0f95c80-fe49-11e8-950b-ede9811cf1a0.png)

Layer that goes before ironing happens:
![image](https://user-images.githubusercontent.com/3779847/49889277-c3739600-fe49-11e8-9ca4-a2cd569e4cde.png)

Layer where ironing happens:
![image](https://user-images.githubusercontent.com/3779847/49889290-ce2e2b00-fe49-11e8-920c-d39d3b8802f6.png)

How it looks after printing:
![2018-12-12 19 49 42](https://user-images.githubusercontent.com/3779847/49889314-df773780-fe49-11e8-87e0-517e8d928805.jpg)

As you can see the weird bridge infill things are present..

#### STL/Config (.ZIP) where problem occurs
Config is default(prusa MK2.5) only with ironing set. Infill is set to 100%.

[fans.zip](https://github.com/supermerill/Slic3r/files/2672995/fans.zip)

**Comment by Murloc992** [comment]
Interestingly enough, default Slic3r PE does not have these bridges at all..

![image](https://user-images.githubusercontent.com/3779847/49890462-c7ed7e00-fe4c-11e8-815d-c3433063f374.png)

**Comment by Murloc992** [comment]
[3mf_file.zip](https://github.com/supermerill/Slic3r/files/2673104/3mf_file.zip)

Here you go. :)

**Comment by Murloc992** [comment]
You also seem to have a '++' profile. Custom default settings?

**Comment by supermerill** [comment]
Seems to be the "only one perimeter on top surface" that create that bug.
I'll look at it for the next release.
For the settings, I have many test settings and no "main" one.

**Comment by Murloc992** [comment]
Yeah, that seems to be the issue. Thanks for looking into it. I love this version of Slic3r so much I wish I had found it sooner. :)

**Comment by photog0411** [comment]
Hi, also query about the ironing feature.

What speed setting will apply to ironing?  I have my top solid infill set to 30mms speed, and my sparse infill set to 200mms speed, but looking at the gcode preview, it appears that the speed of 200mms is being applied to the top (ironing) layer. Is this supposed to be that way?

**Comment by supermerill** [comment]
Ironing is done in two steps, one rought, one fine.
The first pass use the solid infill, the second one use the top solid infill.

**Comment by photog0411** [comment]
> 
> 
> Ironing is done in two steps, one rought, one fine.
> The first pass use the solid infill, the second one use the top solid infill.

I guess maybe it's bug then in visual preview of gcode speed.

See here for example. I have solid infill set to 180mms, and top infill set to 30mms. But in gcode preview, it shows the top most infill as the red color for speed which is 180mms. Or am I reading it wrong and confused?

![capture](https://user-images.githubusercontent.com/18505956/50045398-17f05e80-0060-11e9-97e1-5cdc60dbd4f7.PNG)
![capture0](https://user-images.githubusercontent.com/18505956/50045399-17f05e80-0060-11e9-9d38-5aac3ee6ab7c.PNG)

**Comment by photog0411** [comment]
Ok thank you, I must have missed the smaller lines because hard to see.

One final question:  With Ironing should I be using a fast speed or slower speed? I'm never used cura (which I think this attempts to duplicate) so I'm not sure how it's supposed to work, and if your method is exactly same as cura.

I know with standard solid top infill (no ironing) generally we want slower speed for better detail, but I'm not sure if ironing is supposed to be fast.

**Comment by supermerill** [comment]
I had good result with top infill speed at ~30mm/s (on my prusa mk2).

**Comment by supermerill** [comment]
I fixed the bug. It was a very little area that was considered as unsupported, so it was grow to anchor it into the part. I added a check to remove any bridge infill if it's thinner than a single line.

**Comment by LaserBee** [comment]
It works fantastic now, thank you very much!
