### ISSUE TITLE
Exiting SuperSlicer after job is sent to Octoprint causes it to restart the entire print

### ISSUE THREAD

**Issue by paulonezero** [supermerill/Slic3r#1611]
**Describe the bug**
Exiting SuperSlicer causes the print job sent to Octoprint to restart 

**To Reproduce**
1. Send job to Octoprint via Superslicer (print after upload option enabled)
2. Wait some time for it to start printing
3. Exit SuperSlicer
4. Printer goes back to start of GCODE

I can actually put Windows to sleep and resume and its fine. It _only_ happens if the SuperSlicer program is exited

**>> Project File <<**
Any STL/GCODE

**Expected behavior**
Exit SuperSlicer, print continues

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by supermerill** [comment]
I never encountered the problem. But i often put the computer to hibernate, i'm not closing it.

What's extremely strange is that there is only one http request when uploading and nothing else afterwards...

Can you start your susi with this command: `superslicer_console.exe --loglevel=3` ?
it should print a " Uploading file" lien every time it send something to octoprint.
Does it write another line like that when you're clicking on the close button?
