### ISSUE TITLE
Enabling seam gap results in crash.

### ISSUE THREAD

**Issue by Exerqtor** [supermerill/Slic3r#1626]
Just tried to enable the new seam gap feature inside filament management so that i can play around with it, but that ends up in throwing a tantrum and crashing the second i click to enable it.

Adding a screenshot, to show the errors:

![crash](https://user-images.githubusercontent.com/41635644/136660261-ccc80f8c-a52b-4965-ae73-5b7794a3c1c8.png)

**Comment by tome9111991** [comment]
same as https://github.com/supermerill/SuperSlicer/issues/1618 ?

**Comment by Exerqtor** [comment]
> same as #1618 ?

Yeah apparently, i only read the title/subject in the Issue list, and well yeah i guess you can see why that didn't tick my repost-o'meter 😆
