### ISSUE TITLE
Width of gap fill

### ISSUE THREAD

**Issue by tome9111991** [supermerill/Slic3r#1639]
hello
am not sure if it will work as expected.

i have a 0.4 nozzle and with disabled "overlapping external perimeter" "also for all perimeter" 
i found this on first layer:
![1](https://user-images.githubusercontent.com/57866234/137170153-67bbb9af-cd1d-464b-9c8c-da48df9e944a.png)

on some other layers:
![Screenshot 2021-10-13 175257](https://user-images.githubusercontent.com/57866234/137170184-64d0c309-b7f7-44c0-b3a8-119802fb0690.png)

max width of a 0.4 nozzle should be 0.4 * 80%
im not sure the 1.4mm line works with 0.4 nozzle

File:
[3DBenchy.zip](https://github.com/supermerill/SuperSlicer/files/7339771/3DBenchy.zip)

**Comment by tome9111991** [comment]
Yes with unckeck he try to make one big line.
but maybe there should be a maximum width?
If the option check

**Comment by supermerill** [comment]
> related to #1642 ?

yes, it's an idea i had when looking at your questions here.

it can be big because a loop can be 2 * width as it's a loop. 
The ideal solution is #342, so that the loop can have variable width for the "return" part. But not easy, and need special gcode rules.
