### ISSUE TITLE
Unpredictable results with interior brim options.

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#165]
### Version
_2.2.47.1_

### Operating system type + version
_macOS Catalina 10.15.3_

### 3D printer brand / version + firmware version (if known)
_not relevant_

### Behavior
* _Generating brim inside holes doesn't seem to work, and "Interior brim width" doesn't seem to work well._
* _Steps needed to reproduce the problem_
  * _Place an object on the bed that has openings inside the bottom layer (I have attached an example step file)._
  * _Select "Brim inside holes" or enter a non-zero value in "Interior brim width"._
  * _Hit "Slice now""._

* _Expected Results_
  * _With the "Brim inside holes" option, the brim should be generated inside the holes with the same width as the external brim._
  * _With "Interior brim width" a brim of the desired width should be generated in the internal openings of the first layer._

* _Actual Results_
  * _The "Brim inside holes" function doesn't seem to work_
  * _"Interior brim width" function doesn't generate brim on all internal perimeters and it seems to work only in internal perimeters close to X = 0. Complex shapes seem ignored by the generation algorithm._

Here "Brim inside hole" is active
<img width="1974" alt="Schermata 2020-02-10 alle 10 37 10" src="https://user-images.githubusercontent.com/14921654/74138335-b723ce00-4bf1-11ea-934a-00794315f2b3.png">

Below the "Interior brim width" option is set to 3mm. The object is presented rotated in different angles. Depending on the position, the brim is generated partially, always in different areas.
<img width="1974" alt="Schermata 2020-02-10 alle 09 48 38" src="https://user-images.githubusercontent.com/14921654/74138583-2994ae00-4bf2-11ea-93b9-47aec56778d4.png">

<img width="1974" alt="Schermata 2020-02-10 alle 09 49 03" src="https://user-images.githubusercontent.com/14921654/74138801-87c19100-4bf2-11ea-8f95-39bff3f147be.png">

<img width="1974" alt="Schermata 2020-02-10 alle 09 49 21" src="https://user-images.githubusercontent.com/14921654/74138919-ba6b8980-4bf2-11ea-8f81-c6fe7733e5d9.png">

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
[Brim inside holes.zip](https://github.com/supermerill/Slic3r/files/4180023/Brim.inside.holes.zip)

**Comment by supermerill** [comment]
thank you for the report, i'll look at it asap.

**Comment by liftbag** [comment]
Just a mention, but the problem is still present inthe  version 2.2.48.1.

![SS](https://user-images.githubusercontent.com/14921654/77830205-3b40ff00-7127-11ea-9184-e7fd18f83e15.PNG)

**Comment by liftbag** [comment]
Oh, and it would be of great use, precisely in the printing of gears, to be able to insert only the brim inside the holes, so as to have the profile of the teeth clean, but at the same time to ensure a better adhesion of the lightened gears.
Here I tried to insert only brim into the holes, setting the brim width to zero and interior brim width to 4mm.

![SS2](https://user-images.githubusercontent.com/14921654/77830528-72b0ab00-7129-11ea-9cf0-46fabc6aa5f0.PNG)

![SS3](https://user-images.githubusercontent.com/14921654/77830533-77755f00-7129-11ea-8593-f9fffa134720.PNG)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/77832518-0177f480-7137-11ea-8619-68a40d801e46.png)

i wrote '=' instead of 'add' ...

**Comment by liftbag** [comment]
Solved! Thanks @supermerill. Closing.
