### ISSUE TITLE
 2.2.47.1 Mac build won't open

### ISSUE THREAD

**Issue by royal32** [supermerill/Slic3r#167]
### Version
 2.2.47.1 (Untested MacOS build)

### Operating system type + version
MacOS Catalina 10.15.3

### Behavior
When trying to launch the .app, MacOS reports "The application “Slic3r++.app” can’t be opened."

I solved the problem by performing a _chmod +x_ on _Slic3r++.app/Contents/MacOS/slic3r++_

Also, the app icon didn't load, which can be fixed by capitalizing the _s_ in  _Slic3r++.app/Contents/resources/slic3r.icns_ because the _CFBundleIconFile_ in _Info.plist_ references _Slic3r.icns_ with a capital.

**Comment by liftbag** [comment]
The permission issue is already solved in the latest actions bynary download. #155
