### ISSUE TITLE
questions and comments on your fork

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#17]
Not really an issue per se but can't find a way to send a message to a user on GitHub.

Just wondering if at all you could make a guide in your spare time, that shows the differences between your fork and the official slic3r PE, like what features are new, and where to find them, and what each feature does. I found a few new features, and it's nice that the tool tips have a brief description, but they don't really go in-depth to what the features really do. 

I really like what you are doing, you definitely have added some things I wish Prusa would add to their fork of slic3r.

Do you think there's any way to add an option to make holes diameter bigger or smaller based on preference? My holes always come out about .30mm smaller than I design them once I print them and if there was a way to adjust that in slicing it would be immensely helpful.

Also by the way one of your options has a typo in English language, it is in as "briging" but should be "bridging" I'm not sure where it was.

**Comment by photog0411** [comment]
Thanks! I didn't realize you already had XY hole compensation feature. I will definitely try that one out, that is really promising. I also didn't see that you had the wiki, I'll check that over. 

I found a few other typo bugs for English language, as well. If you want to give me contributor access I can fix them for you and make a commit to a new branch and you can check it out and pull them into your main branch, or else I could fork your fork and fix them and you can look them over if you don't want to give me contributor access.

That's good to know that you merge all the Prusa Slic3rs into your fork when they are released. I just got confirmation from the devs of the official Prusa Slic3r that they will be adding an undo/redo feature to the next main release, so that will definitely be something we will want into your fork as well.

One final question for now: Do you have the netfabb STL fixing built into your fork or was it removed? I was looking for that earlier while trying to fix a model but didn't see it, maybe a bug if it's supposed to be there?

**Comment by supermerill** [comment]
> If you want to give me contributor access I can fix them for you and make a commit to a new branch and you can check it out and pull them into your main branch, or else I could fork your fork and fix them and you can look them over if you don't want to give me contributor access.

you can fork, correct, commit, push and pull request. I will then merge them.
note: i didn't add the new text into the translation file yet, it's inside the code (mainly optiongroup.cpp).

> Do you have the netfabb STL fixing built into your fork or was it removed?

I don't know. Same as slic3rPE.

**Comment by photog0411** [comment]
ok, pull request done.

**Comment by photog0411** [comment]
> enter somthing in the "hole XY compensation" (advanced tab)

Tried this feature out for real today with hole test.  

Before, my holes was all printing about .30mm undersized. So I add +.30mm to the hole XY compensation. Now, all my holes 4mm in diameter or bigger are near perfectly sized -/+ 0.05mm, but holes 3mm and smaller print way too big, like 3mm hole is print 3.30mm and 1mm hole is print 1.70mm.

I wonder if there's ability to add another checkbox where the hole compensation could only be applied to holes with diameter >4mm ?

**Comment by supermerill** [comment]
> 1mm hole is print 1.70mm.

Without the hole compensation, the printed diameter was 1.1mm?
Maybe we should create a table (wanted diameter -> printed diameter) to better understand the hole shrinking.

> I wonder if there's ability to add another checkbox where the hole compensation could only be applied to holes with diameter >4mm ?

Too complicated. 

note: If it's your own design, you should use polygon instead of holes. http://hydraraptor.blogspot.com/2011/02/polyholes.html

**Comment by photog0411** [comment]
> 
> 
> > 1mm hole is print 1.70mm.
> 
> Without the hole compensation, the printed diameter was 1.1mm?
> Maybe we should create a table (wanted diameter -> printed diameter) to better understand the hole shrinking.
> 
> I need more data to change the algorithm.
> 
> note: If it's your own design, you should use polygon instead of holes. http://hydraraptor.blogspot.com/2011/02/polyholes.html

Here's my results of my hole tests:

### No Compensation
1mm hole - filled in can't measure
2mm hole - 1.72mm
3mm hole - 2.73mm
4mm hole - 3.71mm
5mm hole - 4.69mm
10mm hole - 9.71mm

### +.30 Compensation
1mm hole - 1.06mm
2mm hole - 2.27mm
3mm hole - 3.25mm
4mm hole - 3.99mm
5mm hole - 5.01mm
10mm hole - 9.99mm

So we see from these results that the +.30 compensation work great for the 4mm hole, 5mm hole, and 10mm hole, but for some reason it made 1mm hole, 2mm hole, and 3mm hole too big by a lot. Not sure why, doesn't make sense.

I am measuring the top of the piece, of course, I am aware of shrinkage on the bottom (elephant foot).

Your idea of having a table of settings seems like a great idea, that would be really innovative in a slic3r program.

My hole test also prints hexagon holes as well. Im' not sure if the hole compensation also applies to those, but I did see different results. Here are the results for those:

### No Compensation
1mm hole - 0.87mm
2mm hole - 1.97mm
3mm hole - 2.95mm
4mm hole - 3.91mm
5mm hole - 4.83mm
10mm hole - 9.88mm

### +.30 Compensation
1mm hole - 1.07mm
2mm hole - 2.40mm
3mm hole - 3.19mm
4mm hole - 4.17mm
5mm hole - 5.00mm
10mm hole - 10.06mm

**Comment by photog0411** [comment]
@supermerill 

After christmas holiday, will you also be merging the 1.42.0 release of the PE edition into this fork? It looks like they changed a LOT of things in it, a lot of great new features, but it's pretty buggy at the moment. I think you should wait until they have a release candidate version and not alpha.

**Comment by supermerill** [comment]
yes, i already merged most of the code.
