### ISSUE TITLE
Under extrude after import config bundle from PrusaSlicer

### ISSUE THREAD

**Issue by aleung** [supermerill/Slic3r#170]
### Version
2.2.47.1

### Operating system type + version
MacOS 10.14.5

### 3D printer brand / version + firmware version (if known)
Home made Kossel Mini, Marlin 1.1.9

### Behavior

The print was fine with PrusaSlicer-2.2.0-alpha2. I exported the config bundle from PrusaSlicer and imported into Slic3r++. Printed the gcode generated by Slic3r++ and it was under extrude. The neighboring filaments didn't touch each other.

Config bundle, project files and gcodes are in [data.zip](https://github.com/supermerill/Slic3r/files/4261982/data.zip)

Update: I exported the config bundle from Slic3r++ and compared it with the one from PrusaSlicer, found that Slic3r++ had added a lot more parameters. Upload the bundle as well: [Slic3r++_config_bundle.txt](https://github.com/supermerill/Slic3r/files/4262092/Slic3r%2B%2B_config_bundle.txt)

![compare](https://user-images.githubusercontent.com/271538/75452570-82639500-59ad-11ea-96dd-6d176e84861d.jpg)

**Comment by supermerill** [comment]
how much extruded volume was reported by slic3r++ and prusaslicer?
Also, if it's different, i'll need the project file of both. (the .3mf)

**Comment by aleung** [comment]
@supermerill I've uploaded all files and photo above.

The reported used filament had tiny different (~2.4%), but the print looks very different.

> PrusaSlicer
> 
> volume: 7788.19
> Used filament: 1.73m, 4164.57mm3, 5.29g
> 
> 
> slic3r++
> 
> volume: 7788.19
> Used filament: 1.69m, 4064.40mm3, 5.16g

**Comment by supermerill** [comment]
There is a problem when you "convert" the config from slic3r++ to prusaslicer, because some % aren't over the same settings.
The width % is over the layer height in prusa slicer (old behaviour that doesn't make sense anymore) and over the first nozzle width in slic3r++
hence why the first lines didn't have the same width.

Also, it seems like both are under-extruded, it's just a bit less visible on the right, but i don't think the slicer is to blame.

**Comment by aleung** [comment]
I did some more experimental with Slic3r++. Before these tests I had calibrated the extrusion multiplier.

### Left:

- First layer extrusion width: 0.6mm (not use percentage)
- Base layer height: 0.2mm
- First layer height: 0.35mm

### Right:

- First layer extrusion width: 0.6mm (not use percentage)
- Base layer height: 0.2mm
- First layer height: 0.25mm

![IMG_20200228_225413](https://user-images.githubusercontent.com/271538/75563039-975f2780-5a84-11ea-9a37-3ec683168e5e.jpg)

The left side one looks OK, but the right side one is under-extruded. Only different setting is the first layer height.

Both projects in [0228.zip](https://github.com/supermerill/Slic3r/files/4267865/0228.zip)

**Comment by aleung** [comment]
I figured out that the under-extrude was caused by the gap between nozzle and print bed at z=0. Re-calibrate solved the problem. But I don't know why at first PrusaSlicer gave a result better than Slic3r++.
