### ISSUE TITLE
Many unnecessary slicing artifacts with specific model

### ISSUE THREAD

**Issue by SchmartMaker** [supermerill/Slic3r#172]
### Version
Slic3r++ 2.2.47

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
When I load the exact same 3MF file in Slic3r++ and PrusaSlicer, I'm seeing Slic3r++ making unnecessary and undesirable slicing decisions. PrusaSlicer slices my file like I would expect. However, Slic3r++ introduces e.g. artifacts within bridge infill, within solid infill, on top of infill and within and on top of solid infill which affect print speed and possibly print rigidity.

#### Project File (.3MF) where problem occurs

[Tube Cap v2.zip](https://github.com/supermerill/Slic3r/files/4303075/Tube.Cap.v2.zip)

#### Comparison pictures

|Slic3r++|PrusaSlicer|Comment|
|---|---|---|
|![Slic3r 20200308 L08](https://user-images.githubusercontent.com/16756313/76161061-16f99000-6130-11ea-8208-d1064832d8f8.png)|![PrusaSlicer 20200308 L08](https://user-images.githubusercontent.com/16756313/76161081-35f82200-6130-11ea-8a59-d173daead481.png)|Nothing unusual in layer 8.|
|![Slic3r 20200308 L09](https://user-images.githubusercontent.com/16756313/76161085-3e505d00-6130-11ea-9077-4335d8b2f68d.png)|![PrusaSlicer 20200308 L09](https://user-images.githubusercontent.com/16756313/76161091-45776b00-6130-11ea-8fe9-b6cad49b757e.png)|Layer 9 has gaps in bridge infill.|
|![Slic3r 20200308 L10](https://user-images.githubusercontent.com/16756313/76161096-4f996980-6130-11ea-9d48-95264b671a33.png)|![PrusaSlicer 20200308 L10](https://user-images.githubusercontent.com/16756313/76161101-5d4eef00-6130-11ea-935e-794f8203e12d.png)|Layer 10 has two unnecessary perimeters in solid infill close to the object border.|
|![Slic3r 20200308 L11](https://user-images.githubusercontent.com/16756313/76161105-66d85700-6130-11ea-9bb4-82aa19a08a8e.png)|![PrusaSlicer 20200308 L11](https://user-images.githubusercontent.com/16756313/76161106-6b9d0b00-6130-11ea-8fc8-c490997eb4b0.png)|Layer 11 has superfluous gap fill in the top solid infill.|
|![Slic3r 20200308 L12](https://user-images.githubusercontent.com/16756313/76161108-70fa5580-6130-11ea-99f2-27bf492f89c5.png)|![PrusaSlicer 20200308 L12](https://user-images.githubusercontent.com/16756313/76161115-78b9fa00-6130-11ea-82f5-48832f97d30a.png)|Layer 12 puts unnecessary solid infill on top of the gap fill.|
|![Slic3r 20200308 L13](https://user-images.githubusercontent.com/16756313/76161123-840d2580-6130-11ea-8793-ca4d4479c96c.png)|![PrusaSlicer 20200308 L13](https://user-images.githubusercontent.com/16756313/76161134-94250500-6130-11ea-9a7d-5880c76ee015.png)|Nothing unusual in layer 13.|

**Comment by supermerill** [comment]
image 2 & 11) it's because the default anchor size ( harcoded to 3mm in prusaslicer) is lower in slic3r++ to remove some unnecessary fill. If you ant it, you have to put a bigger number. It's in the infill tab, in "anchor" line.

other iamges) It's because you use "only one perimeter on top surface", so the other perimeters are pushed back. Remove perimeters or uncheck the option.
