### ISSUE TITLE
Empty layers at 0.4000 on every model I've tried

### ISSUE THREAD

**Issue by neophyl** [supermerill/Slic3r#180]
### Version
2.2.48

### Operating system type + version
Windows 10  build 1908

### 3D printer brand / version + firmware version (if known)
Prusa MK3

### Behavior
On every slice attempt on every model Ive tried I get an Empty Layers Detected, the output would not be printable error message pop up.

Empty layers detected, the output would not be printable.
Object name: CalibrationCube_v2.stl
Print z: 0.400000
This is usually caused by negligibly small extrusions or by a faulty model. Try to repair the model or change its orientation on the bed.

Even with things like calibration cubes etc that worked fine in the past.

[CalibrationCube_v2_slicer_plus.zip](https://github.com/supermerill/Slic3r/files/4392635/CalibrationCube_v2_slicer_plus.zip)

**Comment by supermerill** [comment]
change in slicing -> XY comp. -> first layer, add a '-'.
In my version, it shrink if negative, but not always in prusaslicer.
But it shouldn't do that anyway, will investigate
