### ISSUE TITLE
Experimental feature request: double continuous perimeter

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#184]
Some friends of mine have thought up an extrusion strategy to build a closed loop wall with a continuous extrusion action, without interruptions, as happens in vase mode.
Although it is impossible to achieve the aesthetic result of a true spiral-shaped movement, we wondered if continuous action could produce a superior aesthetic result compared to the usual slicing strategies. The aim is to have potted objects with sturdy walls.
We decided to ask it here for the dynamism that characterizes this excellent fork of PrusaSlicer.
If you think it is worth trying to evaluate the results, we are a group that could experience the results.

I attach a screen shot of the continuous transition from one layer to another.

![2020-03-30 23 05 37](https://user-images.githubusercontent.com/14921654/77961975-007fc800-72db-11ea-8b78-941bcf49d23e.jpg)

https://myhub.autodesk360.com/ue298421b/g/shares/SHabee1QT1a327cf2b7afd210163a4a40374?viewState=NoIgbgDAdAjCA0IDeAdEAXAngBwKZoC40ARXAZwEsBzAOzXjQEMyzd1C0AjANgA4BWXN0YATALQAzAMb9%2BYgCwR5AJjGNcMAMxqAnPwi5l3KZv7ydaAL4gAukA

**Comment by liftbag** [comment]
Just to give credit to whoever had the idea (yatuin), I am attaching the discussion in which it was born.

https://community.pathio.xyz/t/double-wall-vase/102

**Comment by supermerill** [comment]
it's going from "internal perimeters first" to "external periemter first"
in the first layer, the external perimeter is pushing against the inner wall, and not in the second layer. So you may see a great inconsistency in the perceived external perimeter thickness because of that.

It's possible but will take a good amount of time to force this result, and i'm not convinced that the "jump" from the first to second layer will not be much more noticeable than the current impl.

**Comment by liftbag** [comment]
> it's going from "internal perimeters first" to "external periemter first"
> in the first layer, the external perimeter is pushing against the inner wall, and not in the second layer. So you may see a great inconsistency in the perceived external perimeter thickness because of that.
> 
I started having your same doubts after opening the feature request.
It is probably best to focus your efforts on something else. If you deem it appropriate, I will close the issue.

**Comment by supermerill** [comment]
closing for now. If you have something new for that, you can re-open it.
