### ISSUE TITLE
looping perimeters makes a single line in air

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/Slic3r#185]
### Version
2.2.48

### Operating system type + version
win 10
### 3D printer brand / version + firmware version (if known)
klipper, happens with all

### Behavior
When looping perimeters is on i have a file that makes 1 line in the air, i don't think that is intentional right?

![image](https://user-images.githubusercontent.com/43273303/78011783-576db780-7344-11ea-9df0-a2eeb08e61ab.png)

#### Project File (.3MF) where problem occurs

[DK_Maker_Visir_V0.7 6pc.zip](https://github.com/supermerill/Slic3r/files/4408077/DK_Maker_Visir_V0.7.6pc.zip)

**Comment by supermerill** [comment]
where is the line in the air?

**Comment by Coffee0297** [comment]
The blue lines? 
![IMG_20200331_130321](https://user-images.githubusercontent.com/43273303/78461845-b3319b00-76cc-11ea-910c-d6d8f2257760.jpg)

**Comment by Coffee0297** [comment]
@supermerill no i have that off. blue is overhang preimeter

-Tonny

**Comment by supermerill** [comment]
ok, i'll lokk at this bug.
