### ISSUE TITLE
Feature request: brim override via modifiers

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#186]
### Version
_next releases (actual 2.2.48.1)_

### Operating system type + version
_Any_

### 3D printer brand / version + firmware version (if known)
_Any_

### Request
When printing multiple objects at the same time, it would be helpful, sometimes, to be able to determine which object should have the brim and which should not,
I was wondering if a simple method to implement it, could be to insert the brim parameters into the modifiers.
In this way, it would be sufficient to load the same object as a modifier and assign the desired brim parameters.

_Is this a new feature request?_
Yes

**Comment by supermerill** [comment]
Will look to see if it's possible.

**Comment by liftbag** [comment]
Thanks @supermerill. It works with the latest nightly build. Brim ears and brim inside holes don't seem to work, but I probably need to understand how they work. I will investigate.

<img width="1129" alt="Schermata 2020-05-09 alle 14 54 54" src="https://user-images.githubusercontent.com/14921654/81474403-87db2800-9205-11ea-9900-6003200ab688.png">

<img width="1168" alt="Schermata 2020-05-09 alle 14 54 35" src="https://user-images.githubusercontent.com/14921654/81474410-9295bd00-9205-11ea-92af-24dbebac5ca9.png">

**Comment by liftbag** [comment]
@supermerill there is probably an oversight. Skirt and brim settings also appears in the layer height modifier, although it is not accepted.

**Comment by liftbag** [comment]
Brim ears works well. I still don't understand how brim inside holes works.

<img width="1101" alt="Schermata 2020-05-09 alle 15 28 23" src="https://user-images.githubusercontent.com/14921654/81475090-223d6a80-920a-11ea-8632-dbc01f70b213.png">

**Comment by supermerill** [comment]
"brim inside holes", when activated allow "external brim" to be lay down even if it's inside a hole (surrounded by something).
If you use the modifiers, you may need to have the exact same settings for the inner object and the outer one (if they are two different objects)

**Comment by liftbag** [comment]
Feature request fully integrated for me. I'm going to close.
@supermerill  we have a telegram group on slic3r++ (and PrusaSlicer) and this feature is highly appreciated. Thanks again.
