### ISSUE TITLE
Thin wall discarded.

### ISSUE THREAD

**Issue by rongith** [supermerill/Slic3r#188]
### Version
2.1.44 (perhaps before) to 2.2.48

### Operating system type + version
Win10x64

### 3D printer brand / version + firmware version (if known)
PrusaMK3s

### Behavior
I don't know if that is a feature not well understood or a bug. Some walls are discarded because they are "thin walls". The area is designed with some "selective infill" technique.

With "Overlapping perimeters" unticked and "Thin walls" unticked, the case that bothered me:
![image](https://user-images.githubusercontent.com/7966342/78412330-3e4e5a80-7613-11ea-9e88-47f0f64afdc3.png)

With "Overlapping perimeters" ticked and "Thin walls" unticked:
![image](https://user-images.githubusercontent.com/7966342/78412392-75bd0700-7613-11ea-9104-688941cea5bc.png)

With "Overlapping perimeters" unticked and "Thin walls" ticked:
![image](https://user-images.githubusercontent.com/7966342/78412486-d2202680-7613-11ea-9466-854b0d0b3b12.png)

With "Overlapping perimeters" ticked and "Thin walls" ticked:
![image](https://user-images.githubusercontent.com/7966342/78412525-f4b23f80-7613-11ea-9b57-57b4df6ed8b3.png)

#### Project File (.3MF) where problem occurs
[03802-r01j - 030-Lint50-I3D.thinwall.3mf.zip](https://github.com/supermerill/Slic3r/files/4430360/03802-r01j.-.030-Lint50-I3D.thinwall.3mf.zip)

**Comment by supermerill** [comment]
work as intended.
in 1st case, it's too thin to extrude with perimeters, and you say "i don't want thin walls"

**Comment by rongith** [comment]
Ok Thank you. I wasn't aware that you can even suppress thin walls. 

It is just that I sliced my part with that new version but with settings updated from an older version. I didn't notice the change in handling thin feature. I just updated slic3r, slice and print. But my parts came out differently from the parts I printed with previous version. There were no thin walls on the 9 parts I printed (20-24h print).

Forgot to close, my bad.
