### ISSUE TITLE
Ironing making holes in the top layer

### ISSUE THREAD

**Issue by rlesac** [supermerill/Slic3r#19]
Using 1.41.2-1 I get random places where ironing will "burn" through the top layer.
Do you have any suggestions on how to avoid it?
I changed the top solid speed from 40 to 60mms, and it improved things a bit.
I've set this print to be a bit overextruded and bumped the infill/perimeters overlap to 50% so there should be enough plastic to cover it nicely when ironed.

In Cura 60mms works fine for ironing.

Here are examples:
![20181216_184811](https://user-images.githubusercontent.com/10945003/50057407-465a6080-016a-11e9-99b7-45a39894f672.jpg)
![20181216_184702](https://user-images.githubusercontent.com/10945003/50057408-465a6080-016a-11e9-91b7-14c053603876.jpg)
![20181216_184625](https://user-images.githubusercontent.com/10945003/50057409-465a6080-016a-11e9-9afe-2bbd9b46fdb5.jpg)

**Comment by rlesac** [comment]
I apologize, I have somehow missed the wiki, and sure enough it deals with the aforementioned issue. Will try the print again tomorrow.

**Comment by rlesac** [comment]
After some testing, these are my results:
The over-bridge flow ratio seems to have resolved the ironing issues over sparse infill.

I still have the issue when using thin models with 3 solid layers (0.6mm) and using ironing. 
I upped the flow a bit, but could not get a  good print with only 3 layers and ironing. 
I got around the issue by using 4 layers and that seems to help, but it's not ideal.

Cura ironing has no such issues.

Do you have any ideas or recommendations?

**Comment by supermerill** [comment]
> Cura ironing has no such issues.

I didn't try their ironing. From what i have seen in reddit, some users have the same issue. (https://www.reddit.com/r/3Dprinting/comments/926nqe/cura_ironing_neosanding_issues_holes_scars/)

> Do you have any ideas or recommendations?

I need some pics of the remaining problems & .3mf to give a useful advice (plater->export as .3mf).

**Comment by photog0411** [comment]
would creating a separate speed setting for ironing only be possible I wonder? For those of us that use a lot of profiles it might be helpful

**Comment by supermerill** [comment]
It's possible. Maybe i can store the value for each pattern and change it on the fly in the gui.
