### ISSUE TITLE
Customizabile automatic arrange distance

### ISSUE THREAD

**Issue by guestisp** [supermerill/Slic3r#196]
When automatically arranging multiple objects on the plate, they are kept too far away.
A new parameter to set how many millimeters to use between object would be great.

Most of the time there is no need to use some centimeters, 1mm is even too much :-)

**Comment by supermerill** [comment]
Seems easy, the setting seems to be here but is hidden (duplicate_distance)

**Comment by guestisp** [comment]
Thank you, i will try manually very soon. Is that value in millimeters?

**Comment by supermerill** [comment]
seems like it. But i'm not sure it's within reach of the user. Maybe via command line....

**Comment by guestisp** [comment]
It's not in ini config somewhere?

**Comment by supermerill** [comment]
it's not added in the list of available settings, so it's not possible to add it as-is i the ui.
I think it's the same for the config file.
