### ISSUE TITLE
Seam positions not working as expected

### ISSUE THREAD

**Issue by ogland** [supermerill/Slic3r#197]
Using recent versions of Slic3r++, seam positions are behaving in an unpredictable way. Corner doesn't hide in corners, aligned doesn't really align as in Prusa Slicer and random seam isn't randomized but rather aligned.

2.2.47.0 and earlier is behaving more like Prusa Slicer. Not sure random is randomized though.

Rendered result:
![image](https://user-images.githubusercontent.com/37978198/79310399-27094a00-7efc-11ea-8d19-228dd4517e8f.png)

2.2.47.0 and earlier is better, but not as expected:
![image](https://user-images.githubusercontent.com/37978198/79310372-1bb61e80-7efc-11ea-8960-ec8e4ffb9eaf.png)

Prusa Slicer:
![image](https://user-images.githubusercontent.com/37978198/79310417-31c3df00-7efc-11ea-8621-394b23534e9f.png)

**Comment by ogland** [comment]
This is random seam on a different object, same behaviour with only one object:
![image](https://user-images.githubusercontent.com/37978198/79310528-68015e80-7efc-11ea-9035-6dbc936da49d.png)

**Comment by supermerill** [comment]
Random isn't random anymore.

Didn't find any behavior problems on other ones.

"aligned doesn't really align as in Prusa Slicer": what is exactly the problem ?

**Comment by ogland** [comment]
It's not aligning in inner corners, so the behavior isn't as easy to design
for as it isn't predictable.

Den tors 16 apr. 2020 20:49Merill <notifications@github.com> skrev:

**Comment by ogland** [comment]
Aligned seam is even more far off now in the latest pre-release version. It doesn't prioritize inner corners at all it seems like.
![image](https://user-images.githubusercontent.com/37978198/111276073-37a7d000-8637-11eb-8260-39d170a13722.png)
