### ISSUE TITLE
Config and config bundle export is broken

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#209]
### Version
_2.2.49 [nightly build #215 bridge_speed always available]_

### Operating system type + version
_macOS Catalina and win10 Pro build 10240_

### 3D printer brand / version + firmware version (if known)
_Any. Tested also with fresh install for Prusa i3 MK3S_

### Behavior
* _The config and config bundle export seems broken_
* _Steps needed to reproduce the problem_
  * _Open the slicer_
  * _Choose File > Export > Export config... or Export config bundle..._
* _Expected Results_
  * _config.ini or config_bundle.ini should be generated_
* _Actual Results_
  * _a warning window opens with the following error_

![Cattura](https://user-images.githubusercontent.com/14921654/80274894-1451fa80-86de-11ea-9c9e-c2da9beac80c.PNG)

The problem also occurs after the total deletion of the configuration folder, and resetting to the default settings for a Prusa FFF printer.

_Is this a new feature request?_
No

**Comment by sonictrain** [comment]
Same problem on Linux aswell.

**Comment by ashinhood** [comment]
Same problem on Windows x64 version

**Comment by liftbag** [comment]
Problem solved with the #205 nightly build. Thanks @supermerill.
