### ISSUE TITLE
error in function Slic3r::ExtruderEntityCollection::as_polyline   when using support

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#21]
### Version
1.41.2 Supermerill edition

### Operating system type + version
windows 10

### Behavior

I can't use any support, or I get this error. It won't let me export the gcode and it also doesn't let me preview the gcode.

I don't get this error in official slic3r PE, only your fork.

![1](https://user-images.githubusercontent.com/18505956/50310709-d2bd9980-0470-11e9-872b-6b2351cdcee1.PNG)
![2](https://user-images.githubusercontent.com/18505956/50310708-d2bd9980-0470-11e9-905a-80da956067a3.PNG)

**Comment by photog0411** [comment]
Happens with every .stl file

**Comment by photog0411** [comment]
I'm assuming because it only happens in your fork, it must be one of your custom settings I have enabled elsewhere interfering with the support being generated successfully. I'm not sure which though. I disabled a bunch of them but still getting the error

**Comment by supermerill** [comment]
I'm not at my home this week. I will see if I can patch it.
I modified a bit the support (to allow collection inside them). Maybe the recent changes broke something.

**Comment by photog0411** [comment]
No rush. For now I use main slicer PE

**Comment by supermerill** [comment]
cannot reproduce.
![cannotreprocude](https://user-images.githubusercontent.com/6536403/50354470-f1449300-054b-11e9-869e-a14c1a885742.png)

can you export the platter -> .3mf?

**Comment by photog0411** [comment]
> 
> 
> cannot reproduce.
> ![cannotreprocude](https://user-images.githubusercontent.com/6536403/50354470-f1449300-054b-11e9-869e-a14c1a885742.png)
> 
> ![cannotreprocudegcode](https://user-images.githubusercontent.com/6536403/50354525-1b965080-054c-11e9-9050-a027c92ed99e.png)
> 
> can you export the platter -> .3mf?

No problem, I can't upload here so try this link to 3mf download:
https://transfernow.net/67bl01s81m5w It expires after 2 days.

Pardon the model I used for this, I know it can be printed without support by rotating it, but it is a support test model.

**Comment by supermerill** [comment]
reproduced.

Problem is in the skirt. You can remove it to slice successfully.

**Comment by photog0411** [comment]
i can confirm, removing the skirt does fix it .

Any idea why I can use skirt in official prusa fork, but not this fork? Seems like a bug.

**Comment by supermerill** [comment]
It's complicated. Basically, i made some part of the codebase more generic (to handle ironing, i.e. two infills in one) and this function wasn't modified accordingly.
I will make a new release quickly.

**Comment by photog0411** [comment]
Take your time, man, it's not a big deal now that we're know it can be
fixed by removing skirt.
