### ISSUE TITLE
macOS face mask edition (#201) appears damaged

### ISSUE THREAD

**Issue by liftbag** [supermerill/Slic3r#216]
### Version
_2.2.49  face mask edition_

### Operating system type + version
_macOS Catalina 10.15.4_
### Behavior
* _The macOS version linked on the release page appears to be damaged and does not work_

<img width="572" alt="Schermata 2020-04-30 alle 18 35 37" src="https://user-images.githubusercontent.com/14921654/80738900-ef161f80-8b15-11ea-8a0d-5bc108716b9f.png">

The warning window reads:
"Slic3r ++" is damaged and cannot be opened.
You should move it to the trash

**Comment by supermerill** [comment]
I modified the text in the release page.
Until someone with a mac can compile or tell me why it doesn't work, i don't know what to do.

**Comment by lincolnep** [comment]
> I modified the text in the release page.
> Until someone with a mac can compile or tell me why it doesn't work, i don't know what to do.

I have a mac and should have enough skills to compile it will have a look at it and let you know how i Go

**Comment by georgebashi** [comment]
The 2.2.49 release dmg binary works fine for me on High Sierra (10.13.6). Maybe it's something to do with the notarization requirements on newer macOS releases?

**Comment by liftbag** [comment]
Well, the latest nightly build #215 bridge_speed always available works fine on macOS Catalina.
Can I close the issue?

**Comment by supermerill** [comment]
if the issue resolve itself, sure.
