### ISSUE TITLE
[Feature Request] No Z-lift on first and last layers.

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#22]
Sorry for being annoying. I'm by no means trying to make you work hard, just throwing out ideas out there to improve the overall slic3r experience, and your fork is my favorite so far.

Something I think would be useful is a feature where you can control the Z-lift to not happen on the last layer, to help prevent blobs at the top of big flat prints.

Currently there is a setting for z-lift where you can enable it only on a Z-MM range, but it's not very intuitive because you have to change it for every part you print, and look at the part to calculate what layers correspond to the correct MM.

Far more easier would be just a setting (checkbox) where you could disable Z-lift on the first and last layers (or for each).

**Comment by supermerill** [comment]
I can do it easily for the top solid infill.
It's a bit more complicated for the perimeters, as a perimeter can be half on a top surface a half inside a volume.
