### ISSUE TITLE
Some GUI elements are hidden on a laptop screen

### ISSUE THREAD

**Issue by DeviousPenguin** [supermerill/Slic3r#223]
### Version
Version: 2.2.49
Build: slic3r++_2.2.49_2020-05-01

### Operating system type + version
Operating System: Macintosh
System Architecture: 64 bit
System Version: macOS Catalina Version 10.15.4 (Build 19E287)

### 3D printer brand / version + firmware version (if known)
Longer LK4 Pro running Klipper

### Behavior
Preview Mode has GUI elements: 'Travel', 'retractions', '?' that are off the edge of the screen, and unable to use them, here's a screenshot:

![Screenshot 2020-05-03 at 11 06 55](https://user-images.githubusercontent.com/11376139/80911767-69ba8700-8d30-11ea-9de8-27986489321f.png)

This may be because I'm on a laptop with a smaller screen, but would it be able to make the 'show: extrusion type' bit of the GUI a little thinner so the rest of the GUI can be seen?

#### Project File (.3MF) where problem occurs
This happens with each and every file 

Thanks

**Comment by supermerill** [comment]
It's complicated and will takes days to do that correctly.
I think you may have more luck if you test it with prusaslicer and ask for that in the prusa branch.
I merge against prusaslicer at every release.

**Comment by supermerill** [comment]
or maybe ir's because i enlarged the combo box (extrusion type here) ... i'll look at make it small on small screens

**Comment by DeviousPenguin** [comment]
Thanks, I've downloaded PrusaSlicer and it does look like it has a smaller combo box:

![Screenshot 2020-05-03 at 16 57 37](https://user-images.githubusercontent.com/11376139/80918941-62f73880-8d5f-11ea-8b7a-094aa81d3c50.png)

However I'm still unable to see all the options, so I'm not really sure what the solution is here, maybe move the tickboxes onto the row below or the sidebar? 

Anyway I'll try and request some sort of fix in the prusa branch, thanks. :)

**Comment by supermerill** [comment]
i reopened it to let me not forgot to reduce the combo size

**Comment by supermerill** [comment]
Wasn't that hard. But no translation for cropped labels.

**Comment by DeviousPenguin** [comment]
Thank you very much, I've just updated to the latest build and looks great now, even on my tiny screen! :)

![Screenshot 2020-05-14 at 15 26 09](https://user-images.githubusercontent.com/11376139/81946555-6b6d3000-95f7-11ea-97d3-1f9480a4d4f5.png)
