### ISSUE TITLE
bug:  custom start gcode under printer not saving

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#24]
### Version
1.42.0-alpha2

### Operating system type + version
win64

### Behavior
custom start gcode under printer not saving when profile is saved. It just reverts back to whatever the last input was when profile is reloaded.

This is happening in 1.42.00 alpha2 supermerill edition.

It is not happening in officla slic3rPE 1.42.00 alpha1. I have not tested official alpha2 PE yet.

**Comment by photog0411** [comment]
Also, it appears ctrl+A (to select all text) is no longer working in the gcode text boxes. Possibly related.

**Comment by photog0411** [comment]
> Corrected yesterday by prusa. Will be fixed in the next version.

ok thanks brother. I didn't know if this was also present in the prusa edition or just your fork -- I searched the prusa GitHub issue list but didn't see it posted, maybe I was using the wrong terms.

**Comment by Patrik-svobodik** [comment]
@supermerill it looks like you almost abandoned this project, I hope it is not true but I have not seen any progress or merging of the master

**Comment by supermerill** [comment]
@Patrik-svobodik ?
https://github.com/supermerill/Slic3r/releases

**Comment by Patrik-svobodik** [comment]
@supermerill thanks, I see your progress on Zaribo-firmware, why dont you merge them together? Or are they already merged?

**Comment by Patrik-svobodik** [comment]
Sorry, I mixed up two repos in my head

**Comment by photog0411** [comment]
Thanks, it's prusa's error and they corrected it.

**Comment by Brainlazy** [comment]
Although fixed in "Brim Ears edition" the recent pre-release, "Support edition", seems to manifest this problem again.

**Comment by supermerill** [comment]
for the time being, you can ctrl+maj+a
