### ISSUE TITLE
Post-Processing Support?

### ISSUE THREAD

**Issue by clarkent86** [supermerill/Slic3r#2414]
### What happened?

Post-processing does not work as documented for Slic3r, but the option is present.
SuperSlicer does not come with a Perl executable so out of the box I needed to add the it. Once it is present, I get errors.
I also was able to get the Python example running without errors, but there are no output files generated as expected even without encountering errors and a full path given to the `-o` option.
I would expect the documentation [here](https://manual.slic3r.org/advanced/post-processing) to work.

### Project file & How to reproduce

Following documentation [here](https://manual.slic3r.org/advanced/post-processing) in addition to adding a Perl executable to the root of the SuperSlicer directory and trying both perl and python examples.

### Version

2.3.57.2

### Operating system

Windows 10

### Printer model

n/a

**Comment by supermerill** [comment]
The doc isn't crystal clear, but `They just need to be recognized by your system as an executable and accept the path to the G-code file as the only argument.` so unless your .py is recognise as 'executable' by your os (and wille xecute it with python, you have to use python.exe or use a bat/sh script file.

begin easy, add a hello.bat next to superslicer.exe, with `echo "hello world %1" > echofile.txt"` inside and enter `hello.bat` in your post-processing field.
