### ISSUE TITLE
need confirmation - alpha3 shows up as alpha2?

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#25]
### Version
1.42.0 alpha 3 - I THINK!

### Operating system type + version
win64

### Behavior

I installed the latest 1.42.0 ALPHA 3  release but it's showing up in the program as alpha 2 still? I just want confirmation if you are getting this too, or if maybe the release was compiled wrong.

![capture](https://user-images.githubusercontent.com/18505956/51078712-ee8b1880-1687-11e9-979f-da83195bdf3e.PNG)

**Comment by photog0411** [comment]
i downloaded the official slic3r PE alpha 3, and it shows up correctly as the right alpha3 version, so it's not a main fork problem

**Comment by supermerill** [comment]
Seems like prusa forgot to commit/push the file with the new version number. I forgot to verify.

**Comment by photog0411** [comment]
> 
> 
> Seems like prusa forgot to commit/push the file with the new version number. I forgot to verify.

ok, so it's v3 but only says v2?

**Comment by supermerill** [comment]
yes

**Comment by photog0411** [comment]
Ok perfect :)
