### ISSUE TITLE
[Feature Request] HTPLA as filament type, or allow user to set their own custom filament types

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#26]
I use HTPLA as filament often, which requires higher temperature than normal PLA. But Slic3r don't support this filament right now. 

![1](https://user-images.githubusercontent.com/18505956/51359296-1cf86180-1a95-11e9-97d1-e5b017d6d33e.PNG)

Reason for having this as an option would be so that gcode output naming when using placeholders can be differentiated from regular PLA...

![2](https://user-images.githubusercontent.com/18505956/51359319-3699a900-1a95-11e9-92ec-14d314fefc1a.PNG)

I asking you to put it in your fork, rather than in main slic3r, because Prusa never listen to any of my new feature ideas and they just close the topic.

Or better would be if user could actually type in filament name there and it would remember it. I tried typing in "HTPLA" in the box but it just revert back to PLA, because HTPLA is not an option.

**Comment by supermerill** [comment]
It's a bug, should be corrected in a future release.

**Comment by supermerill** [comment]
I tried to correct that but it 's too complicated. It's a gui stuff, and prusa may repair it themself. For now, I'll forfeit and wait to see what prusa will do for that.

**Comment by supermerill** [comment]
I will add some options for the next release.

**Comment by supermerill** [comment]
it's not released yet, but here the future format you should be able to write with the rubber-band:

`[input_filename_base]_20_{if filament_type[0]=~/other0/}HTPLA{elsif filament_type[0]=~/other1/}PLA+{else}{filament_type[0]}{endif}.gcode`

I added other0->other9 to make some room. I hope prusa will be able to make the field editable in the future.


note: the FLEX / SCAFF / PVA make the extrusion speed of the wiping tower slower, so i added also a new field below to be able to control this setting manually.
