### ISSUE TITLE
All the parameters inside the gcode

### ISSUE THREAD

**Issue by robustini** [supermerill/Slic3r#2693]
I tried to search if this request had already been made but I don't find anything similar.
It would be very useful if all the slicing parameters were saved inside the gcode, as if it were a project.
This way it would be possible to extract them for future use.
Maybe you have deleted the 3mf and you only have the gcode, in that way the whole print, filament and printer profile could be detected and saved if necessary.
Simplify3D has this functionality, limited but existing, and many times it has been useful to me, but for a long time only SuperSlicer exists for me.

**Comment by royal32** [comment]
You can already do this from File > Import > Import config, unless I'm misunderstanding the request.

**Comment by robustini** [comment]
It would be enough simply to be able to append to the gcode, or at the beginning the "SuperSlicer.config" ie what is saved in 3mf, obviously with the possibility of being able to import it in case.

**Comment by robustini** [comment]
> You can already do this from File > Import > Import config, unless I'm misunderstanding the request.

Damn, you're right, I didn't really notice, thanks!
There's already the config at the end pf the gcode.
