### ISSUE TITLE
No Internal Perimeters for Whole Object. 2.4.58.4

### ISSUE THREAD

**Issue by Milkbone911** [supermerill/Slic3r#3075]
### Version
2.4.58.4

### Operating system type + version
Windows 10 Pro / 21H2 

### Behavior
Object seems to generate no internal perimeters regardless of which settings are selected. The Previews of the object while slicing does have these perimeters but once its finished slicing it no longer has these perimeters.

![superslicer_Uf5AgU7rY5](https://user-images.githubusercontent.com/4016695/184557347-54508624-e682-433a-a3ce-3cfeddf5e294.png)

Settings:
![superslicer_lXnNhyKFGj](https://user-images.githubusercontent.com/4016695/184557425-64dc0d3b-c388-4ad4-be28-2c1efae36886.png)

Preview during slicing showing all internal perimeters
![superslicer_Zu7r3Mk5KV](https://user-images.githubusercontent.com/4016695/184557459-95a79c8c-f622-41e5-b23e-51438be1cbb3.png)

#### Project File (.3MF) where problem occurs

[Fishing Lure Mold.zip](https://github.com/supermerill/SuperSlicer/files/9334225/Fishing.Lure.Mold.zip)
_

**Comment by neophyl** [comment]
I opened your project in 2.4.58.4 on windows 10 so the same version you are using and its slicing fine with all the perimeters.

**Comment by Dx-Dx-Dx** [comment]
![image](https://user-images.githubusercontent.com/102039778/184710771-9f62072c-218f-4f84-9c97-988c3052d082.png)
U can click feature to enable / disable it in preview.
