### ISSUE TITLE
dragging stl onto slic3r icon no longer works

### ISSUE THREAD

**Issue by photog0411** [supermerill/Slic3r#32]
### Version
Latest release... Support edition

Win64

### Behavior

Can no longer drag stl file onto slic3r icon and have it get opened automatically. Have to now open slic3r first and drag stl file into slic3r window.

Last version before brim ears edition was working fine.

**Comment by 3d-gussner** [comment]
Can confirm that it is not working in Slic3r++ 1.42.0-alpha3.11 on Windows 10 (build 17134), 64-bit edition

**Comment by photog0411** [comment]
working good in the newest release.
