### ISSUE TITLE
Weird gaps in perimeters of all models, but especially benchy

### ISSUE THREAD

**Issue by Murloc992** [supermerill/Slic3r#35]
### Version
1.41.2 

### Operating system type + version
Windows 10 64bit

### Behavior
When printing the lower part (~6mm) of a benchy with Slic3r++ I am getting some interesting gaps.

The gaps are not appearing when using Slic3r PE 1.41.2 with identical .ini files as they use the same settings folder.

This is a comparison picture:
![2019-02-03 13 13 54](https://user-images.githubusercontent.com/3779847/52176338-09016f00-27ba-11e9-83c6-54427bee5409.jpg)

SLic3r++ is on the right.

To reproduce it, just print the included small part of 3D benchy, it's a small print and a short one too.

I am wondering, maybe it's a settings issue? Yet disabling small gap detection and enabling thin walls did nothing.

I now have a ton of benchy bottoms trying to witch hunt this. :)

#### STL/Config (.ZIP) where problem occurs
[bugreport.zip](https://github.com/supermerill/Slic3r/files/2825478/bugreport.zip)

**Comment by supermerill** [comment]
Can you test with tjhe seam to "hidden" (it's the default setting for slic3rPE, i just renamed it)?

also, can you send me your two gcode files? (the one with the good benchy, and the one with the bad benchy)

**Comment by Murloc992** [comment]
I will do it when I find the time, meanwhile another issue has risen, I will make a report soon..

**Comment by Murloc992** [comment]
I have added a comment on the vase mode issue: https://github.com/supermerill/Slic3r/issues/5

**Comment by Murloc992** [comment]
Sorry for not giving an update for so long.. I will try to squeeze some prints inbetween huge orders I have today..

**Comment by supermerill** [comment]
I close this for inactivity.
If someone else find a degradation in a print vs prusaslicer, plaes re-open this issue and post the two project file (.3mf in a zip, from prusaslicer & slic3r++)
