### ISSUE TITLE
Ironing: whispy bits of filament....

### ISSUE THREAD

**Issue by LaserBee** [supermerill/Slic3r#37]
### Version
Slic3r++_1.42.0-alpha4.0_190204

### Operating system type + version
Win 10
### Behavior

Just tried ironing for the first time, and I am getting odd whispy bits of filament deposited on top of the print. The fan is on 100%, so I am wondering if it's blowing some off the extruder? It's a really odd problem, which has never happened before without ironing...

![img_20190209_162813](https://user-images.githubusercontent.com/36974632/52523324-0609f100-2c88-11e9-8461-74d2ef20b970.jpg)

**Comment by supermerill** [comment]
yeah, ironing is buggy on the last version. Get the previous one or wait the next one (2-3 days).

**Comment by LaserBee** [comment]
Thanks for the reply. While I've got you here, can I make a feature request?

The top layer of flat objects is always drawn diagonally, from the lower
left to the top right. Would it be possible to make it draw the top layer
horizontally, so the lines run left to right instead?

**Comment by supermerill** [comment]
for ironing?

for rectilinear, you can use the Angle -> fill setting

**Comment by LaserBee** [comment]
Ah, I hadn't spotted that! That will be a big help, thanks!
