### ISSUE TITLE
Cut UI ignored by keyboard

### ISSUE THREAD

**Issue by Sidic101** [supermerill/Slic3r#40]
### Version
"Boring edition ++"

### Operating system type + version
Windows 10 10.0.17763 build 17763 according to System information

### Behavior
When I click the "Cut" button, I can't set the cut height. Pressing numbers on the numpad rotates the view and does not insert the numbers into the textbox, the number bar numbers do nothing. Pressing delete or trying to use ctrl+v also only affects the scene, not the input texbox.

**Comment by Sidic101** [comment]
I can still use the orange box thingy and change the cut height roughly with the mouse.

**Comment by Sidic101** [comment]
The issue comes from the current build of PE and hasn't yet been fixed https://github.com/prusa3d/Slic3r/issues/1572

**Comment by Sidic101** [comment]
It appears Prusa has fixed the issue, alpha7 is supposed to have it working.

**Comment by Sidic101** [comment]
Prusa has fixed the issue in alpha7.

**Comment by supermerill** [comment]
should be fixed in my latest release, so.
