### ISSUE TITLE
Would lilke to see Adaptive Slicing / Quality added

### ISSUE THREAD

**Issue by OopAck** [supermerill/Slic3r#42]
1.42.0
The Slic3r 1.3.0 has a option under Layers and perimeters
Use adaptive slicing and scroll bar option under called Adaptive quality.

Would like to see these added

**Comment by guestisp** [comment]
+100 for this :)

**Comment by supermerill** [comment]
Not a priority for now. 
I want to do a complete rework of the layer height assignment algo before.

**Comment by supermerill** [comment]
As the code was here, i re-activated it.
Also, prusa is working on something for the next version, so the old algorithm isn't going to stay (i try it a bit, imo it's shitty).
