### ISSUE TITLE
Layer Height to be allowed to Exceed Nozzle Width.

### ISSUE THREAD

**Issue by julianjc84** [supermerill/Slic3r#4342]
**Feature Request.**
Layer Height to be allowed to Exceed Nozzle Width.
example:
LayerHeight 1mm
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/dbca39fa-d30a-4ce4-b51a-931ff6cc4b4a)
Nozzle Diameter Installed on hotend 0.6mm
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/6343259e-501d-4d60-b844-fe6e787064af)

It would be nice to be not restricted by Layer Height and Nozzle Width.
There seems to be no limit of the maximum line width allowed to extrude.
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/63a6526a-5c2c-4104-b9f4-dc37c68587ff)

A 0.6Nozzle can extrude a 2mm width line no problem. Especially with high flow hot ends. Yes there are issues with the "spacing", and manual adjustment of the linewidth spacing in relation to the line width is another consideration issue to consider.

**Describe the solution you'd like**
De-Restrict the relationship between Nozzle Diameter and Max LayerHeight / Allow override.
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/53234779-88b3-44fe-9c74-6617ad62feab)

**Reason For Request**
Aesthetics look for prints.
Big Layer height with small high flow hot ends.
General functional prints where you want alot of plastic
a 0.6Nozzle can really extrude alot of filament.
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/16444396-6469-459d-a620-7af025db7517)

**Comment by supermerill** [comment]
there is multi-extruder printer.
You can print an object with a huge extruder and huge layer, and another one with small extruder and small layer height.
That's why the min/max layer height on the extruder tab is checked (that can be changed from slicing to edit) and then each layer is checked against all theirs used extruders min/max lh.

If you want your 0.6 nozzle to have the behaviour of a 2mm nozzle, just set it to 2mm, no?

**Comment by julianjc84** [comment]
The Nozzle Diameter overrides the layer height limits.
Regardless of Layer height limits when they exceed nozzle diameter. EG: 200% or 10mm
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/0fc61f94-be04-4cc9-bb9a-0ad5fcad3115)
if the Layer Height is greater than nozzle diameter then it wont slice.
![image](https://github.com/supermerill/SuperSlicer/assets/14962510/6fb144da-e89e-4b2e-a27a-36976febd105)

**Comment by supermerill** [comment]
The min/max layer height on the extruder tab is checked on slincing, so it doesn't go higher than the nozzle size.
I can change it so it's checked when someone edit the field, like when you try to set a brim separation gap higher than the brim width.

What i'm try to say is: don't put 200% here, this is an invalid value, as any higher than 100%.

**Comment by julianjc84** [comment]
i don't really understand you sorry. but here is gif example

![superslicer_jTChovgVDy](https://github.com/supermerill/SuperSlicer/assets/14962510/7f076954-48e9-46bd-a23a-e6bd22445e3a)

**Comment by supermerill** [comment]
I'll start again from the beginning.

> It would be nice to be not restricted by Layer Height and Nozzle Width.

There is checks to ensure the shape of the extrusion are feasible.

> A 0.6Nozzle can extrude a 2mm width line no problem. Especially with high flow hot ends. 

then change the nozzle diameter from 0.6 to 2, and everything should work. (the setting, not the real nozzle object in your printer)

>Yes there are issues with the "spacing", and manual adjustment of the linewidth spacing in relation to the line width is another consideration issue to consider.

if it's in % and you change the nozzle diameter, then everything should have changed accordingly.

**Comment by julianjc84** [comment]
I will try some tests.
I believe I understand it now and it should work as expected.

EDIT: yes works as you say.

Thankyou.
