### ISSUE TITLE
Mac OS Seqouia Update 15.1

### ISSUE THREAD

**Issue by Horusei** [supermerill/Slic3r#4471]
### What happened?

After updating MAC OS, progranm cannot be started anymore.

The Program Finder does not have permission to open from "(null)"-< tranlated from german

### Project file & How to reproduce

Update Mac Os via System Settings

### Version

2.5.59.13

### Operating system

MacOs 15.1

**Comment by Jarery** [comment]
I had same, but by downloading a new version after removing the bed textures (not sure if that made a difference) and running the terminal command : "xattr -cr /Applications/SuperSlicer.app"

Also had to make sure I was using the correct _arm version for an apple M processor

**Comment by Creo2005** [comment]
> ### What happened?
> After updating MAC OS, progranm cannot be started anymore.
> 
> The Program Finder does not have permission to open from "(null)"-< tranlated from german
> 
> ### Project file & How to reproduce
> Update Mac Os via System Settings
> 
> ### Version
> 2.5.59.13
> 
> ### Operating system
> MacOs 15.1
> 
> ### Printer model
> _No response_

the same :(

**Comment by Creo2005** [comment]
On macOS 15.1 need Signed and notarized snapshot build. 
so did openSCAD. And now openSCAD has started. See https://github.com/openscad/openscad/issues/880#issuecomment-2453281962

**Comment by mszulen** [comment]
This should be your fix as mentioned by Jarery: terminal command : "xattr -cr /Applications/SuperSlicer.app"

**Comment by Creo2005** [comment]
> This should be your fix as mentioned by Jarery: terminal command : "xattr -cr /Applications/SuperSlicer.app"

I know it and I did it. Doesn't help. MacOS Sequoia 15.1 Intel

**Comment by Horusei** [comment]
> This should be your fix as mentioned by Jarery: terminal command : "xattr -cr /Applications/SuperSlicer.app"

I also tried and it didn‘t work. Changed Slicer.

**Comment by Horusei** [comment]
Not resolved, Hit the Wrong Button. I already tried this an didnt‘t help. I changed the Slicer.

**Comment by Vannue007** [comment]
Plus 1. “Xattr” don’t work and I’m using a M1 chipset
