### ISSUE TITLE
Axis not printed properly

### ISSUE THREAD

**Issue by fungreenfox** [supermerill/Slic3r#4484]
**Bug description**
Does not print the axis properly

**Expected behavior**
A normal axis expected

!!>> Project File <<!!
*Please* upload a ZIP archive containing the project file used when the problem arise: `File`->`Save project as...`, then zip it & drop it here.  
Please export it just before the problem occur. Even if you did nothing and/or there is no object, export it! (it contains your current configuration).
[SMWheel1.zip](https://github.com/user-attachments/files/17794539/SMWheel1.zip)

**To Reproduce**

Just print from the superslicer image.

**Screenshots**
![image](https://github.com/user-attachments/assets/747f8d4c-f882-40d6-b915-7e89921df73d)

**Desktop (please complete the following information):**
 Windows 10, octoprint, ender 6.
**Additional context**

**Comment by legend069** [comment]
this is not a "slicer" issue.
you will need to tune your settings. i'd suggest starting with min_layer_time and turn up the part cooling.

**Comment by fungreenfox** [comment]
Thank You.
