### ISSUE TITLE
Unnecessary internal solid infill layers

### ISSUE THREAD

**Issue by fpikus** [supermerill/Slic3r#46]
Version
Slic3r++ 1.42.0-a6

Operating system type + version
Windows 10 64-bit

3D printer brand / version + firmware version (if known)
Prusa Mk2.5 (not relevant, this is slicing issue)

Behavior
Slicing the attached model. Prusa version of Slic3r generates solid infill around the tops and bottoms of the holes in small circles (at heights around 5.6mm). Slic3r++ generates several layers of solid infill, using top infill pattern for one of them - an octogram spiral layer buried in the middle of the print (see attached screenshots). 
I tried disabling anchor size or using the default anchor size, no difference.

Slic3r++:
![image](https://user-images.githubusercontent.com/39199330/53395969-1ee8f680-3958-11e9-9350-c0e7838f8ad5.png)
![image](https://user-images.githubusercontent.com/39199330/53396136-8e5ee600-3958-11e9-8ee6-beca3d542824.png)

Prusa:
![image](https://user-images.githubusercontent.com/39199330/53396047-5657a300-3958-11e9-9402-c641073287d3.png)
![image](https://user-images.githubusercontent.com/39199330/53396110-7d15d980-3958-11e9-97ef-2b51a05e5d8a.png)

[Tool stand.3mf.txt](https://github.com/supermerill/Slic3r/files/2904281/Tool.stand.3mf.txt)

# Project File (.3MF) (or stl+config) where problem occurs

**Comment by supermerill** [comment]
Seems to be the "extra perimeters" that go full-steam on the number of perimeter: It adds a perimeter to the part/layer as long as it detects an overhang. I have to make it a bit less perimeter-happy (to only draw them on overhang areas). Will come soon©.

You can uncheck the option for now.
