### ISSUE TITLE
extruder clearance 

### ISSUE THREAD

**Issue by DrMarkyMarc** [supermerill/Slic3r#48]
Version
Version of Slic3r Prusa Edition used 1.42.0-alpha 6.0

Operating system windows 10

Behavior
Arrange not working properly with auto clearance setting. 
Steps needed to reproduce the problem
Pressing the arrange button or the shortcut (A)
Expected Results
normal arrangement. They just do normal setting like we had not put any value in clearance.

**Comment by supermerill** [comment]
prusa fix that in their latest release.
