### ISSUE TITLE
Vase mode broken

### ISSUE THREAD

**Issue by supermerill** [supermerill/Slic3r#5]
![slic3r](https://user-images.githubusercontent.com/6536403/45548369-63f2f380-b824-11e8-9823-b2756718933b.jpg)
When slicing in vase mode, the line are not joined and too many layer are created.

Probably something related to the "last layer at exact height" function
![slic3r](https://user-images.githubusercontent.com/6536403/45548345-4de53300-b824-11e8-8c9b-af128ba63065.jpg)

Also, it seems this function doesn't update the flow if the height is changed (0.2mm -> 0.25 and it underextrude)

Solutions: 
* short-term : deactivate it
* long-term: redo it.

**Comment by Murloc992** [comment]
This issue is still valid on 1.4.2 alpha 4.

I have no exact layer marked.

![image](https://user-images.githubusercontent.com/3779847/52367337-80522f80-2a54-11e9-8503-9aa9ae71335b.png)

**Comment by supermerill** [comment]
@Murloc992 : can you post your settings?

**Comment by Murloc992** [comment]
@supermerill Sure.

Here you go:
[bugreport.zip](https://github.com/supermerill/Slic3r/files/2864549/bugreport.zip)

I will add benchy and all the other bug report info soon to their respective issues soon.

**Comment by supermerill** [comment]
I corrected the bug. Note that you don't need to hollow the object to create a hollow cylinder.
