### ISSUE TITLE
Slicing sequential objects skirt is generated around all copies of object

### ISSUE THREAD

**Issue by tomasvilda** [supermerill/Slic3r#51]
Version
1.4.20 alpha 6

Operating system type + version
Windows 10

Behavior
Slicing sequential objects skirt is generated around all objects and not around every sequential object.

Steps needed to reproduce the problem
Create a copy of the object and choose complete individual objects in sequential printing.

Expected Results
Skirt should be around every copy of the object.

Actual Results
One skirt around all sequential objects.

**Comment by supermerill** [comment]
but you won't complain if a skirt is passing by an already finished part?

Maybe automatically deactivating multi-layers skirt is the way to go.

**Comment by tomasvilda** [comment]
There is notification when multiple objects are too close to each other, the same way user could be notified about overlapping skirts. On Cura every copy has it's own skirt.

Without skirt I get mess on the second copy of the object when printing TPU. Skirt cleans the way before printing the second object.

**Comment by supermerill** [comment]
I'll see if i can do something quick. Currently skirt &brim are extruded before everything, so it may be big task.

**Comment by tomasvilda** [comment]
Using alpha 7.0, but the result is the same, one skirt around all individual objects.

**Comment by supermerill** [comment]
![good_skirt](https://user-images.githubusercontent.com/6536403/54400745-a5c20100-46c4-11e9-80cd-b73d0626f877.png)

that's not what you want?

**Comment by tomasvilda** [comment]
Yes that's what I want and you showed workaround, just add as many objects as I want on plate. But that should work on instances also. Because if I add object and add instances I get one skirt around all instances.
