### ISSUE TITLE
Not starting pre-compiled version, MSVCP120.dll is missing

### ISSUE THREAD

**Issue by birtalanelod** [supermerill/Slic3r#56]
Version : Slic3r++_1.42.0-alpha6.0_190221
Not starting pre-compiled version , 
MSVCP120.dll is reported missing
![image](https://user-images.githubusercontent.com/34862871/54078625-a5dc8e00-42cb-11e9-9d5b-ad71cf1da10d.png)

**Comment by supermerill** [comment]
oups.
You can steal it from slic3rPE or microsoft for now.

**Comment by birtalanelod** [comment]
the solution was to install Visual C++ Redistributable Packages for Visual Studio 2013 from this link:
https://www.microsoft.com/en-us/download/details.aspx?id=40784

sorry for posting as an issue, I could just Google it, but instead I went crazy (because  slic3r PE was working)

**Comment by supermerill** [comment]
no problem, i'm glad you post it, i may have forgotten to add it without you.
