### ISSUE TITLE
Rotating an object breaks Sequential Printing clearance check

### ISSUE THREAD

**Issue by Brainlazy** [supermerill/Slic3r#59]
Version
1.42 alpha 7.0

Operating system type + version
Win7 x64

3D printer brand / version + firmware version (if known)
Prusa i3mk3

Behavior
As of alpha 7 rotating an object causes sequential printing to flag objects as causing a collision regardless of position, object size, or extruder clearance settings.
Restoring object rotation to 0 degrees removes the warning and allows the plate to be sliced.
Alpha 6 did not exhibit this error, possibly indicating it is related to the change in skirt logic from #51 

[Tau_big_pulley_clean.zip](https://github.com/supermerill/Slic3r/files/3000879/Tau_big_pulley_clean.zip)

**Comment by supermerill** [comment]
should be okay now, can you test again?
