### ISSUE TITLE
Supporting dense layer spread to too large area

### ISSUE THREAD

**Issue by burner-** [supermerill/Slic3r#63]
Version 1.42.0-alpha7.0
Looks that with Automatic and Automatic, only for small areat supporting dence layer spread to whole print even smaller area is needed to do anchor. Also if there is 1 or 2 layer to next solid it will do "bridge" layer top of previous solid layer. In case where there is solid layer under dense support layer it would be good do detect that there is no need for anchoring.
![dense infill](https://user-images.githubusercontent.com/3836115/56850140-0b7deb80-6907-11e9-8dde-f5b6ab3dd8f1.png)

There is image where these two problems are visible. There is no need for anchoring in this case and specially there is no need to spread that layer to whole object.

**Comment by supermerill** [comment]
I corrected a bug where the selected option wasn't linked to the same option. 

Can you try again or link the model?
