### ISSUE TITLE
Crash when slicing with Slic3r++_1.42.0-rc_190609

### ISSUE THREAD

**Issue by dot-bob** [supermerill/Slic3r#69]
### Version
Slic3r++_1.42.0-rc_190609

### Operating system type + version
Windows 10 Pro

### Behavior
Slic3r crashes when I slice the following project on your recent release.  The same project and or files slice without crashing in PrusaSlicer.

[case.zip](https://github.com/supermerill/Slic3r/files/3270613/case.zip)

**Comment by toskium** [comment]
Version: Slic3r++_1.42.0-rc1

Operating system: Windows 10 pro 1803

Behavior: Slic3r crashes when trying to generate gcode from attached STL files. Alpha7 works fine.

[problematic_stls.zip](https://github.com/supermerill/Slic3r/files/3292987/problematic_stls.zip)
