### ISSUE TITLE
Merge with Slic3rPE 1.41.1 

### ISSUE THREAD

**Issue by tmolberg** [supermerill/Slic3r#8]
Are you planning to merge with the latest release of Slic3rPE again? The new support blocker system seems to be very interesting and would be fantastic to use in combination with your features

### Version
_Version of Slic3r used goes here_
1.41.2 (1.41.0 -> your latest release)
_Use `About->About Slic3r` for release versions_

### Operating system type + version
_What OS are you using, and state any version #s_
Win10 64bit

### Behavior

_Is this a new feature request?_
Yes

**Comment by supermerill** [comment]
yes, but not with the beta. I will merge when the release will be published.

**Comment by supermerill** [comment]
done
