### ISSUE TITLE
Bed model placement

### ISSUE THREAD

**Issue by Sidic101** [supermerill/Slic3r#87]
### Version
1.42.2

### Operating system type + version
Windows 10 version 1903

### 3D printer brand / version + firmware version (if known)
irrelevant

### Behavior
The included bed models are not located at the bed when loaded. 
![image](https://user-images.githubusercontent.com/25415862/63695474-0f6c3c80-c819-11e9-893a-c387ed60db28.png)
![image](https://user-images.githubusercontent.com/25415862/63695533-2e6ace80-c819-11e9-9f20-78012a78b33a.png)

The stock PrusaSlicer 2.0 models behave the same in Slic3r++, considering that I think the issue might be solved by merging with PS2.1.

**Comment by supermerill** [comment]
merging solved that
