### ISSUE TITLE
Ironing issue: small strange holes

### ISSUE THREAD

**Issue by LaserBee** [supermerill/Slic3r#91]
### Version
1.42 STABLE

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Anet A8 (heavily modified)

### Behavior
After ironing, there are slight holes in the print, where you can almost see the layer underneath. I have tried turning the "Above Bridge Flow" up to 1.3, and I have even printed with 100% infill, and still get this. It's not everywhere, but in the badges I have phtographed you can see it's in the top left corner of each. It's not the model, as if I rotate the model it's still in the same area. 

https://photos.app.goo.gl/GjRkhv9qcKGRT7Qx9

Detail:

https://photos.app.goo.gl/8QwejEZAtc6NMF9E8

**Comment by supermerill** [comment]
Maybe your filament is a bit too thin or you are under-extruding a tiny bit.
You may try to turn back the "Above Bridge Flow" up to 1.2 and put 1.05 / 1.1 to filament flow.

I also had this when i print petg in large area, but not with pla & abs. It's with pla for you?

**Comment by LaserBee** [comment]
Yes, it was PLA. I will experiment with your solutions tomorrow, as I've just started an overnight print. 

It seems it only happens on some objects, maybe the object hight is just slightly too short or high?

**Comment by supermerill** [comment]
The object height shouldn't be an issue.
Can you post the .3mf (project file , file -> save as) with at least two objects: a good and a bad one?

**Comment by Quintox303** [comment]
I have experienced this issue too with some PLA prints. It seems in some cases there is not enough filament to fill all the gaps. I have had great success with the following ironing parameters: 
Top Solid Infill: 0.9 percentFlow
Ironing Layer: 0.3 percentFlow

I'll attach some pictures with some test prints that I've done soon

**Comment by LaserBee** [comment]
I replaced the nozzle on my printer, as well as replaced the stepper motor, and it *seems* to be better. My whole printer could use a tune-up.

Quintox, where is the option to adust the ironing layer flow?

**Comment by Quintox303** [comment]
Here are my results! 

So usually slic3r++ prints the top solid infill layer at 70% flow and then does the ironing layer at 30% flow. I found that this wasn't sufficient to fill everything in properly (which you can see in the pictures below), and it resulted in very rough top layers. Almost sandpaper like. I compiled another version of slic3r++ with the top solid infill layer at 90% and the ironing layer at 30% and I got awesome results. The top layer is still matte but not as rough and the extrusion lines are less visible. Here are the pictures:

![IMG_20190907_222920](https://user-images.githubusercontent.com/26502465/64475045-c0cb8480-d1c0-11e9-990f-2312cbf83a76.jpg)
Left: stock, right: 90/30
<br>
![IMG_20190907_222947](https://user-images.githubusercontent.com/26502465/64475049-ce810a00-d1c0-11e9-8935-da97bd3e424f.jpg)
Stock slic3r++, the ironing layer extrusion is not adequately covering the layer below as you can see.
<br>
![IMG_20190907_223015](https://user-images.githubusercontent.com/26502465/64475056-ee183280-d1c0-11e9-8ccb-1da1ab6f40be.jpg)
90/30 version appears to have a much more uniform ironing cover
<br>
![MVIMG_20190907_223047](https://user-images.githubusercontent.com/26502465/64475065-0daf5b00-d1c1-11e9-9161-87fc1d336d0c.jpg)
Stock slic3r++ appears quite rough and has some holes where the infill meets the perimeter
<br>
![IMG_20190907_223056](https://user-images.githubusercontent.com/26502465/64475084-320b3780-d1c1-11e9-8da1-ba682bde5ee0.jpg)
90/30 version these holes where infill meets perimeters are gone.

My extruder was very finely calibrated before running these tests. Please note these pictures have been edited to bring out the details. 

@LaserBee unfortunately right now the ironing layer flow isn't adjustable through the software. I had to edit the parameters in the fillSmooth.hpp file and then rebuild slic3r++ to complete these tests. However that would be an awesome feature if it was configurable in slic3r @supermerill!

I will continue to do some more tests and see if I can get an even better ironing layer

**Comment by supermerill** [comment]
I can easily add a "top layer flow" if needed. I just hoped it wasn't necessary. I will do that for next release.

**Comment by 3dprintrookie** [comment]
I have the exact issue after the latest version. A lot of gaps on the top surface that look quite ugly.

The previous version produced much better ironed top layers.

**Comment by Quintox303** [comment]
I have finished my testing now. I printed about 30 test squares with different settings, comparing slic3r++ results to those from cura and adjusting appropriately. I have achieved best results with the following settings:

top solid infill layer flow: 100%
ironing layer flow: 0%
top solid infill percentWidth: 1.0
ironing layer percentWidth: 4.0 (gives a line width of approx 0.1mm)
ironing layer speed: quite low, around 40mm/s seems to be a good balance of quality and speed.
top layer fan: seems to have no impact on the ironing surface finish

Surprisingly setting the ironing layer line width so low doesn't add a huge amount of print time which is good to see. It does however make the ironing finish tonnes better. It is no longer rough to the touch, it just looks very uniform and slightly matte. 

Having the ironing layer flow set to zero also help rid the issue #96 that I was experiencing a little as well.

It would be great to have the ironing layer flow and also the flow of the layer below it adjustable. I tried adding this functionality myself but it doesn't work properly
![slicer screenshot](https://user-images.githubusercontent.com/26502465/65523332-79b6f080-df2f-11e9-84ee-16d01f2cd9ef.PNG)

In addition to this, I think that when ironing is enabled, the "top solid infill" extrusion width setting should impact the ironing layer only, not the layer below it. The top solid infill speed setting works this way, but not the extrusion width setting. If I set top solid infill extrusion width to 0.1mm then it will also make the solid layer below it 0.1mm.

More test pictures coming soon!

**Comment by 3dprintrookie** [comment]
Can you please push an update for this fix? I’ve been waiting ever since you updated the label as fixed. 

My print suffer a lot from holes on top surface with ironing

**Comment by supermerill** [comment]
fixed in the lastest release. If you have holes, and you can't increase more the over-bridge flow, increase also the top flow.

**Comment by 3dprintrookie** [comment]
Thank you for adding the feature. @Matts-Hub what's the best setting you get with @supermerill latest update? I increased the top flow to 105% to test this out.
