### ISSUE TITLE
Support enforcer not creating support gcode

### ISSUE THREAD

**Issue by toskium** [supermerill/Slic3r#93]
### Version
1.42.2

### Operating system type + version
Windows 10 Pro 1803

### Behavior
The support enforcer should in theory force support right under the overhang. For some reason it does not. It seems model specific (cylindrical overhang) since I tried to enforce support on a simple test object (flat overhang) and that was working as expected.

Green support enforcer:
![support_enforcer](https://user-images.githubusercontent.com/15872792/64079974-ee12c100-ccee-11e9-9fe0-bcde3d89d640.png)

Gcode Preview:
![support_enforcer_gcode_preview](https://user-images.githubusercontent.com/15872792/64079978-f408a200-ccee-11e9-8523-b04f2f130c99.png)

#### Project File (.3MF) where problem occurs
[support_enforcer_bug.zip](https://github.com/supermerill/Slic3r/files/3563753/support_enforcer_bug.zip)

**Comment by supermerill** [comment]
I'll look, i didn't tried this feature yet.

**Comment by supermerill** [comment]
I was a side-effect (a part not well understood) of "no perimeter on bridge area" -> "fill with bridge"
