### ISSUE TITLE
Spacing between multiple objects on buildplate

### ISSUE THREAD

**Issue by Blitzacer** [supermerill/Slic3r#95]
### Version
1.42.2

### Operating system type + version
Windows 10_

### 3D printer brand / version + firmware version (if known)
Prusa I3 MK3S

### Behavior
When i increase the number of copies of an object, after I select "Arrange" the objects are all touching eachother, leaving no gap between them. If i print it like that, they will be fused together.
Am I missing something in the settings? 

![1](https://user-images.githubusercontent.com/49832433/64178012-84aec180-ce58-11e9-8a49-7e68534d7830.png)
![2](https://user-images.githubusercontent.com/49832433/64178013-84aec180-ce58-11e9-87a8-b7e3661e25e6.png)

Thanks.

PS: Any way to get the bed image like prusaslicer?

**Comment by supermerill** [comment]
Reproduced.

> Any way to get the bed image like prusaslicer?

use the prusa profile from this repository, or be sure that it begin with

```
[vendor]
# Vendor name will be shown by the Config Wizard.
name = Prusa {technology}
full_name = Prusa Research {technology} Technology Printers
technologies = FFF; SLA
```

**Comment by Blitzacer** [comment]
> I have it. I'll look if it's not a packaging issue. Do you use the default profile from here or did you import them?

I used a default profile from the inicial wizard.
