### ISSUE TITLE
Colorprint shows all layers as yellow?

### ISSUE THREAD

**Issue by 3dprintrookie** [supermerill/Slic3r#97]
### Version
1.42.2

It seems like colorprint doesn't show various layers at different colors like vanilla PrusaSlicer would, is this being rectified?

![Capture](https://user-images.githubusercontent.com/55085445/64526621-db167700-d314-11e9-8630-d63c0d4c0f46.PNG)

**Comment by supermerill** [comment]
It was a bug with the "filament", that occur at the gui change a year before.
