### ISSUE TITLE
[Feature Request] Configurable overhang detection

### ISSUE THREAD

**Issue by Billiam** [supermerill/Slic3r#99]
### Version
1.42.2

### Request

Allow the overhang amount to be configurable, instead hardcoding to 50% of nozzle width: 

https://github.com/supermerill/Slic3r/blob/01e61068dafa2c024614c9a332d9468ed705204a/src/libslic3r/PerimeterGenerator.cpp#L75

This would allow more control over fan speed for prints that use minimal fan for strength, but need cooling for overhangs smaller than 1/2 the nozzle width.

**Comment by supermerill** [comment]
note that it also changes the extrusion from "flatty" to "cylinder".

**Comment by supermerill** [comment]
Done in latest release.
